### ISSUE TITLE
var MHPluginSDK = require('NativeModules').MHPluginSDK;

### ISSUE THREAD

**Issue by ZCLegendary** [MiEcosystem/ios-rn-sdk#1]
NativeModules 模块在哪里呢?运行的时候提示 MHPluginSDK is not an Object

**Comment by tls6a** [comment]
NativeModules 是oc导出的模块，你是用米家app测试的吗？米家app导出了这个模块

**Comment by ZCLegendary** [comment]
请教一下,要真机测试的话,是不是首先要讲做好的模块上传到米家开发者平台呢?还是通过其他的方式进行调试? rn 模块要怎样才能够调试呢

**Comment by marteswang** [comment]
请问你是米家的注册开发者么？个人的还是哪个公司的？这个SDK目前还不是完全公开自己能够接入的，需要有米家开发者账号，通过开放平台创建产品、插件等一系列操作才能够真机调试的。请访问 http://open.home.mi.com 了解详情。

祝好！

在 2017年3月14日，下午9:02，ChuangZhang <notifications@github.com<mailto:notifications@github.com>> 写道：


请教一下,要真机测试的话,是不是首先要讲做好的模块上传到米家开发者平台呢?还是通过其他的方式进行调试? rn 模块要怎样才能够调试呢

**Comment by ZCLegendary** [comment]
您好 有个问题请教下 iOS 该怎样做性能测试呢?我看文档中没有提到这一点

**Comment by Copypeng** [comment]
inactivity
