### ISSUE TITLE
sdk中可以引入其他外部组件吗，比如说react-native-linear-gradient

### ISSUE THREAD

**Issue by camilarSummer** [MiEcosystem/ios-rn-sdk#10]
sdk中可以引入其他外部组件吗，比如说react-native-linear-gradient
尝试过直接npm install这个组件，失败，
然后尝试过在package.json中的dependencies中加入这个，然后重新npm start --reset-cache，失败
请问如果出现需要引入外部组件的需求，改如何处理

**Comment by Copypeng** [comment]
可以使用兼容 React Native 0.25.0 版本的第三方纯 js 开源组件，不能使用包含 Native 代码的组件。
