### ISSUE TITLE
用什么样的方式保持设备不断开连接？

### ISSUE THREAD

**Issue by sofichael** [MiEcosystem/ios-rn-sdk#100]
**环境条件**
- app版本: [e.g. v4.5.0/DB]  
- 相关模块和API: [e.g. MHBluetoothLE.startScan  MHBluetoothLE.connect]

**问题描述**

IOS 通过蓝牙扫描的方式，成功连接蓝牙设备，连接成功后，大概10秒左右会自动断开
通过设备列表绑定的方式，连接不会断开。为什么？

**使用方法**
1. MHBluetoothLE.startScan 扫描到该设备
2.MHBluetoothLE.connect 连接成功
3.发送、接收指令
...
自动断开连接

**期望**
用什么样的方式保持设备不断开连接？

**Comment by LiuMengzhou** [comment]
猜测是用了小米蓝牙协议，但是没使用sdk封装的相应方法去连接吧。

小米蓝牙设备绑定后，再连接设备，固件端叫“登陆”。使用MHBluetooth模块，直接使用其中的连接方法，比如scanAndConnectForSeconds。

MHBluetoothLE 模块就是coreBluetooth的封装，没有小米蓝牙协议的“登陆”过程。需要配合使用MHXiaomiBLE模块的loginXiaoMiBLE方法。可以参考com.xiaomi.corebledemo.ios

**Comment by sofichael** [comment]
@LiuMengzhou  好的，谢谢
我是用小米蓝牙协议首次绑定的，再次进入用scanAndConnectForSeconds连接，可以使用。
