### ISSUE TITLE
getAvailableFirmwareForDids接口 获取otaProgress 一直为0

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/ios-rn-sdk#101]
## Bug Report
调用startUpgradingFirmwareWithDid接口给WiFi模块升级固件后，调用
getAvailableFirmwareForDids 获取相应的ota进度

**实际现象**
getAvailableFirmwareForDids 获取的 otaProgress 的值
在otaStatus 从 "downloading" 到 "installed" 过程中一直为0，
固件端确定有上报，
服务器端也确定有返回，

**期望表现**
进度随着升级逐渐从0变大

**环境**
- app版本: [v4.5.0/db，v4.8.7/AppStore]
- 相关模块和API: [ MHPluginSDK.getAvailableFirmwareForDids]

**复现步骤**
1. 进入门锁插件-更多页面-门锁设置-WiFi配置
2. 点击WiFi固件版本红点去升级
3. 升级进度从0% 过一段时间后直接跳到升级成功

**其他的上下文/日志/截图**
## 插件代码
```js  
MHPluginSDK.getAvailableFirmwareForDids([MHLockManager.lockWifiDid], (res, json) => {
      console.log(json)
      if (res && json.length > 0) {
        let updateInfo = json[0]
        if (updateInfo.updating) { // 正在更新
          this.setState({
            progress: updateInfo.otaProgress
          })
          this.upgradingTimeoutId = setTimeout(() => {
            this.getUpgradeProgress()
          }, 500)
        } else {
          this.sendUpgradeCmd('02')
          this.setState({
            status: 'upgradeSucc'
          })
          DeviceEventEmitter.emit('wifiUpdateSucc')
        }
      }
    })
```
## 插件端log内容
`
![22561539077292_ pic_hd](https://user-images.githubusercontent.com/15864191/47146646-183dd900-d2ff-11e8-8d04-f56f6c84d4f5.jpg)
`

## 设备端log
![22631539080043_ pic_hd](https://user-images.githubusercontent.com/15864191/47146686-2b50a900-d2ff-11e8-9b5c-66a93f54db07.jpg)

## 服务器log

```
INFO	20181009 18:05:24.000	app	E4YgHXD5TNSiQtjDq8yWvg	113.87.162.206	/app/home/multi_checkversion	SESSION	{"UA":"iOS-11.3-4.5.0-iPhone9,2--39C4972BEFC3FAAE63EFE67EDF83271C708EF1C7-840907289","context":{"_device_read_borrow":0,"_device_read_cost":9,"_device_read_count":1,"_locale":"zh_CN","_login_ip":"113.87.162.206","_login_uid":840907289,"_protocol":"HTTP2","_redis_call":3,"_redis_cost":0},"cost":"14ms","data":{"dids":["101726695"]},"err":"","httpStatus":200,"locale":"zh_CN","nonce":"6v14IkLIoYkBh2h9","ret":{"code":0,"message":"ok","result":{"list":[{"did":"101726695","updating":true,"curr":"1.3.3_0001","latest":"1.3.4_0002","description":"提升固件稳定性\n","isLatest":false,"ota_progress":20,"ota_status":"downloading","ota_failed_code":0,"ota_failed_reason":"","timeout_time":180,"ota_start_time":1539079524,"force":false}]}},"userId":840907289}	miot/httpserver/filters.Logger.func1:329	840907289	

INFO	20181009 18:05:26.000	app	Y0ZnOaahQVOw3Ym7qAbA2A	113.87.162.206	/app/home/multi_checkversion	SESSION	{"UA":"iOS-11.3-4.5.0-iPhone9,2--39C4972BEFC3FAAE63EFE67EDF83271C708EF1C7-840907289","context":{"_device_read_borrow":0,"_device_read_cost":9,"_device_read_count":1,"_locale":"zh_CN","_login_ip":"113.87.162.206","_login_uid":840907289,"_protocol":"HTTP2","_redis_call":3,"_redis_cost":0},"cost":"14ms","data":{"dids":["101726695"]},"err":"","httpStatus":200,"locale":"zh_CN","nonce":"/////+KvzkYBh2h9","ret":{"code":0,"message":"ok","result":{"list":[{"did":"101726695","updating":true,"curr":"1.3.3_0001","latest":"1.3.4_0002","description":"提升固件稳定性\n","isLatest":false,"ota_progress":40,"ota_status":"downloading","ota_failed_code":0,"ota_failed_reason":"","timeout_time":180,"ota_start_time":1539079524,"force":false}]}},"userId":840907289}	miot/httpserver/filters.Logger.func1:329	840907289	

INFO	20181009 18:05:41.000	app	AgpSiItvT7G963BKSvKEQQ	113.87.162.206	/app/home/multi_checkversion	SESSION	{"UA":"iOS-11.3-4.5.0-iPhone9,2--39C4972BEFC3FAAE63EFE67EDF83271C708EF1C7-840907289","context":{"_device_read_borrow":0,"_device_read_cost":9,"_device_read_count":1,"_locale":"zh_CN","_login_ip":"113.87.162.206","_login_uid":840907289,"_protocol":"HTTP2","_redis_call":3,"_redis_cost":0},"cost":"13ms","data":{"dids":["101726695"]},"err":"","httpStatus":200,"locale":"zh_CN","nonce":"VVGISEyNcmUBh2h9","ret":{"code":0,"message":"ok","result":{"list":[{"did":"101726695","updating":true,"curr":"1.3.3_0001","latest":"1.3.4_0002","description":"提升固件稳定性\n","isLatest":false,"ota_progress":60,"ota_status":"installing","ota_failed_code":0,"ota_failed_reason":"","timeout_time":180,"ota_start_time":1539079524,"force":false}]}},"userId":840907289}	miot/httpserver/filters.Logger.func1:329	840907289	

INFO	20181009 18:05:43.000	app	F1VjiLSIQLymtWFsTS_9Nw	113.87.162.206	/app/home/multi_checkversion	SESSION	{"UA":"iOS-11.3-4.5.0-iPhone9,2--39C4972BEFC3FAAE63EFE67EDF83271C708EF1C7-840907289","context":{"_device_read_borrow":0,"_device_read_cost":9,"_device_read_count":1,"_locale":"zh_CN","_login_ip":"113.87.162.206","_login_uid":840907289,"_protocol":"HTTP2","_redis_call":3,"_redis_cost":0},"cost":"270ms","data":{"dids":["101726695"]},"err":"","httpStatus":200,"locale":"zh_CN","nonce":"JrSJ9AaphTIBh2h9","ret":{"code":0,"message":"ok","result":{"list":[{"did":"101726695","updating":true,"curr":"","latest":"1.3.4_0002","description":"提升固件稳定性\n","isLatest":false,"ota_progress":99,"ota_status":"installed","ota_failed_code":0,"ota_failed_reason":"","timeout_time":180,"ota_start_time":1539079524,"force":false}]}},"userId":840907289}	miot/httpserver/filters.Logger.func1:329840907289	
```

**尝试过的解决办法**

<!--业务-WiFi固件升级>

**Comment by damiknows** [comment]
![22561539077292_ pic_hd](https://user-images.githubusercontent.com/15864191/47147906-d6faf880-d301-11e8-8cb9-406fa9ea2c0e.jpg)
补充下设备的log图

**Comment by LiuMengzhou** [comment]
@damiknows 首先感谢你提出issue。很抱歉没有及时回复。

你的插件代码好像写的有点问题，请问你贴出了全部代码吗？

**Comment by damiknows** [comment]
@LiuMengzhou 补全了代码如下：

辛苦帮忙看看哪里有问题

`
class MHLumiWifiUpgradePage extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.isNeedHandleWifiStatusReport = true;

    this.latestInfo = null
    this.state = {
      latestVersion: null,
      currentVersion: null
    };


  }

  componentWillMount() {
  }
  
  componentDidMount() {
    this.addEventListener()
    MHPluginSDK.showLoadingTips(LocalizedStrings['check.ungrading'])
    this.getLatestVersion()
  }
  


  componentWillUnmount() {
    if (this.lockEventListener) this.lockEventListener.remove()
    if (this.upgradingTimeoutId) clearTimeout(this.upgradingTimeoutId)
    if (this.state.status === 'upgrading') this.sendUpgradeCmd('04')
    this.clearSendUpgradeCmdTimeout();
  }

  addEventListener () {
    this.lockEventListener = DeviceEventEmitter.addListener(MHGlobal.MijiaLockDeviceEventEmitter, (body) => {
      console.log(body)
      
      if (body[0] == MHLockUtils.EventEnum.SendSyncHardware) { // 同步硬件信息
        if (result !== MHGlobal.LumiLockErrorSuccess) {
          MHPluginSDK.showFailTips(LocalizedStrings['get.wifidid.fail']);
        }
      } else if (body[0] == MHLockUtils.EventEnum.StartWifiUpdate) { //发送开始升级命令
        if (body[1] === MHGlobal.LumiLockErrorSuccess) {
          //设备升级成功后设备还会上报这里屏蔽一下
          if (this.state.status !== 'upgradeSucc' || this.state.status !== 'upgrading') {
            this.startSendUpgradeCmdTimeout(60000)
          }
        }else {
          this.clearSendUpgradeCmdTimeout();
          this.setState({
            status: 'upgradeFail',
            errorMsg: LocalizedStrings['upgrade.fail']
          })
        }
      } else if (body[0] == MHLockUtils.EventEnum.WifiConfigResult) {

        //每次升级只处理一次wifi 模块连接上云端的消息
        if (!this.isNeedHandleWifiStatusReport) {
          return;
        }
        if (body[1] === '03') {
          this.clearSendUpgradeCmdTimeout();
          this.isNeedHandleWifiStatusReport = false;
          if (this.state.status !== 'upgradeSucc' && this.state.status !== 'upgradeFail') this.startUpgrading()
        } 
        // else if (body[1] !== '04') {
        //   this.setState({
        //     status: 'upgradeFail',
        //     errorMsg: LocalizedStrings['upgrade.fail']
        //   })
        // }
      }

    })

  }

  getUpgradeProgress () {
    MHPluginSDK.getAvailableFirmwareForDids([MHLockManager.lockWifiDid], (res, json) => {
      console.log(json)
      if (res && json.length > 0) {
        let updateInfo = json[0]
        if (updateInfo.updating) { // 正在更新
          this.setState({
            progress: updateInfo.otaProgress
          })
          this.upgradingTimeoutId = setTimeout(() => {
            this.getUpgradeProgress()
          }, 500)
        } else {
          this.sendUpgradeCmd('02')
          this.setState({
            status: 'upgradeSucc'
          })
          DeviceEventEmitter.emit('wifiUpdateSucc')
        }
      }
    })
  }

  startUpgrading () {
    this.setState({
      status: 'upgrading',
      progress: 0
    })
    MHPluginSDK.startUpgradingFirmwareWithDid(MHLockManager.lockWifiDid, (res, json) => {
      console.log(res)
      console.log(json)
      if (res && json === "ok") {
        this.getUpgradeProgress()
      } else if (res && json === "already latest") {
        this.setState({
          status: 'new'
        })
      } else if (!res) {
        this.sendUpgradeCmd('03')
        this.setState({
          status: 'upgradeFail',
          errorMsg: json.message
        })
      }
    })
  }

  getLatestVersion () {
    MHPluginSDK.getAvailableFirmwareForDids([MHLockManager.lockWifiDid], (success, result) => {
      MHPluginSDK.dismissTips()
      if (result && result.length > 0) {
        let updateInfo = result[0]
        if (updateInfo.updating) {
          this.setState({
            status: 'upgrading',
            progress: updateInfo.otaProgress
          })
          this.upgradingTimeoutId = setTimeout(() => {
            this.getUpgradeProgress()
          }, 500)
        } else {
          let data = {
            currentVersion: updateInfo.currentVersion,
            latestVersion: updateInfo.latest
          }
          if (updateInfo.isLatest) {
            data.status = 'new'
          } else {
            data.status = 'upgrade'
            let upgradeLog = updateInfo.desp.split(/\r\n|\r|\n|\n\r/g)
            data.upgradeLog = upgradeLog
          }
          this.setState(data)
        }
      } else {
        MHPluginSDK.showFailTips(LocalizedStrings['check.upgrade.fail'])
      }
    });
  }


  sendUpgradeCmd (status) {
    this.setState({
      status: 'upgrading',
      progress: 0
    })
    this.isNeedHandleWifiStatusReport = true;
    MHLockManager.wifiFirmwareUpgrade(status);
    this.startSendUpgradeCmdTimeout(6000);
  }

   /*超时处理*/
  startSendUpgradeCmdTimeout(time){
    this.clearSendUpgradeCmdTimeout()
    this.sendUpgradeCmdTimeout = setTimeout(() => {
      this.sendUpgradeCmdTimeout = null;
      this.setState({
        status: 'upgradeFail',
        errorMsg: LocalizedStrings['upgrade.fail']
      })
    }, time)  

  }

  clearSendUpgradeCmdTimeout() {
    if (this.sendUpgradeCmdTimeout) {
      clearTimeout(this.sendUpgradeCmdTimeout)
    }
  }

`

**Comment by LiuMengzhou** [comment]
@damiknows 大概看了一眼没看出什么问题。

你可以试试改一下循环调用的时间。
```diff
- this.upgradingTimeoutId = setTimeout(() => {
-   this.getUpgradeProgress();
- }, 500);

+ this.upgradingTimeoutId = setTimeout(() => {
+   this.getUpgradeProgress();
+ }, 1500);
```

然后`getLastVersion`函数里面为什么也要循环调用`getUpgradeProgress`？


最后在MarkDown里面写代码的格式是:
![image](https://user-images.githubusercontent.com/13726966/47332639-7c232180-d6b2-11e8-909f-2de286f45de2.png)

**Comment by damiknows** [comment]
@LiuMengzhou 感谢，我这边马上改一下试试，
然后getLastVersion函数里面为什么也要循环调用getUpgradeProgress？
：用户有可能在升级途中退出页面，但是升级的过程不会中断，
所以下次进来的时候如果升级还在继续则直接显示升级中的UI

**Comment by damiknows** [comment]
@LiuMengzhou 尝试将延时改成2000，获取到了40，100两个进度了，请问延时增加就可以读取到值了，这个可能的原因是什么？

**Comment by LiuMengzhou** [comment]
@damiknows 这个是我猜测的，后台不允许频繁调用接口。

不过，一直递归调用 `getAvailableFirmwareForDids`查询状态本身就不对。
现在已经改成了事件通知，我明天给你一个iPA和文档，你试一下吧。请留下邮箱。

**Comment by damiknows** [comment]
@LiuMengzhou 不好意思，回复晚了，这是我的邮箱：hao.gu@aqara.com，感谢

**Comment by damiknows** [comment]
通过监听MHPluginSDK.upgradeEvent完美解决

**Comment by LiuMengzhou** [comment]
> 通过监听MHPluginSDK.upgradeEvent完美解决

🤟
