### ISSUE TITLE
从设备列表打开设备，404

### ISSUE THREAD

**Issue by shjsyxj** [MiEcosystem/ios-rn-sdk#104]
**check [docs](https://github.com/MiEcosystem/ios-rn-sdk/tree/master/MiHomePluginSDK/docs) before issue**

## Support Question

**环境条件**
- app版本: [e.g. v4.8.9]
- 相关模块和API: [e.g. ---]

**问题描述**
从设备列表打开设备展示出：
Cannot GET/com.xxx.xxx.ios/index.html

pc服务器端展示404：
192.168.21.106 - - [25/Oct/2018:09:39:12 +0000] "GET /com.xxx.xxx.ios/index.html HTTP/1.1" 404 43 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B93 APP/com.xiaomi.mihome APPV/4.8.9 iosPassportSDK/3.3.5 iOS/11.1 miHSTS MIOTStore/20180406 (SmartHome;4.8.9;bfb1d09100b7d2d8a27190b97ce99452666bd152;20181024181107;I;345B3A87-0BE7-47BC-8753-0882BA7FF61B;) MIOTWeex/1.3.1 (SmartHome;4.8.9;bfb1d09100b7d2d8a27190b97ce99452666bd152;0.18.0;I;345B3A87-0BE7-47BC-8753-0882BA7FF61B;) iOS/11.1 MiHome/4.8.9 iPhone/iPhone9,1 DeviceId/BFB1D09100B7D2D8A27190B97CE99452666BD152 UserId/226236445"

**使用方法**
下载了SDK,创建了项目包，根据iOS拓展程序开发指南，

npm start --reset-cache // 启动了服务器
在测试手机中，开启开发者选项，按要求输入调试拓展程序信息。
在设备列表中单击对应设备，弹出ALERT框，点击 “我知道了”。

**尝试过的解决办法**
1.在项目根目录新建index.html,此时插件可加载出新创建的index.html。
2.新建RN项目，可以成功运行。

**其他的上下文/日志/截图**

提供更多的上下文，有日志或者截图更好。

**Comment by LiuMengzhou** [comment]
看日志可能是打开了商城相关的调试开关。请关闭后重试。
如图：
![641540535268_ pic_hd](https://user-images.githubusercontent.com/13726966/47548355-63717080-d92b-11e8-9ac4-c2f270701449.jpg)
![651540535269_ pic_hd](https://user-images.githubusercontent.com/13726966/47548365-6bc9ab80-d92b-11e8-91e2-f9ce6f49c6d7.jpg)

**Comment by shjsyxj** [comment]
关闭商城模式以后，依然出现这个问题。

::ffff:192.168.21.104 - - [29/Oct/2018:03:08:16 +0000] "GET /com.xxx.xxx.ios/index.html HTTP/1.1" 404 43 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B93 APP/com.xiaomi.mihome APPV/4.8.9 iosPassportSDK/3.3.5 iOS/11.1 miHSTS MIOTStore/20180406 (SmartHome;4.8.9;bfb1d09100b7d2d8a27190b97ce99452666bd152;20181025193854;I;345B3A87-0BE7-47BC-8753-0882BA7FF61B;) MIOTWeex/1.3.1 (SmartHome;4.8.9;bfb1d09100b7d2d8a27190b97ce99452666bd152;0.18.0;I;345B3A87-0BE7-47BC-8753-0882BA7FF61B;) iOS/11.1 MiHome/4.8.9 iPhone/iPhone9,1 DeviceId/BFB1D09100B7D2D8A27190B97CE99452666BD152 UserId/226236445"

**Comment by shjsyxj** [comment]
就是上面的操作！成功了， 谢谢你！
