### ISSUE TITLE
APP端删除米家门锁后偶现无法连接，需要杀掉APP重开方可连接

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/ios-rn-sdk#106]
## Bug Report

**实际现象**

偶现从APP端删除米家门锁后，进入添加页面，继续添加刚才删除的门锁，门锁端按了配对键后，APP没有连接(此时扫描设备页面，我的设备下面有刚刚删除的门锁)，需要杀掉APP重新打开方可连接

**期望表现**

APP端删除米家门锁后，重新添加，正常添加

**环境**
- app版本: [v4.8.9/App Store]

**复现步骤**
1. 从设备列表删除门锁
2. 进入添加页面重新添加
3. 按下门锁配对键，APP无连接反应，我的设备下有刚刚删除的设备

**其他的上下文/日志/截图**

删除门锁后的添加蓝牙设备的列表如下图：
![wechatimg2373](https://user-images.githubusercontent.com/15864191/47638356-4b9f2400-db99-11e8-8478-1fb0680e9ffc.jpeg)

**尝试过的解决办法**

杀掉APP重新打开，再添加，添加蓝牙设备页面，没有我的设备，开始添加，添加成功

<!--蓝牙连接，偶现>

**Comment by damiknows** [comment]
补充一下手机信息：
型号： iPhone6Plus
系统：11.4.1

**Comment by Copypeng** [comment]
如果删除了还能看见，是删除时设备没有从内存中移除，应该是我们米家的一个 bug。感谢反馈，我们会跟踪修复这个问题。

**Comment by damiknows** [comment]
@Copypeng 好的，辛苦

**Comment by Copypeng** [comment]
是不是该关issue了？

**Comment by damiknows** [comment]
问题解决了是吗？ @Copypeng
