### ISSUE TITLE
MHPluginSDK.openIftttAutoPage()中部分条件如何进入rn代码里的页面

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/ios-rn-sdk#107]

**Comment by pencilCool** [comment]
你好，不太清楚你说的“部分条件” 是什么意思

**Comment by yanmin0220** [comment]
> 你好，不太清楚你说的“部分条件” 是什么意思

您好，是这样的 ，在小米IOT开发者平台的某个产品自动化设置中配置一条“任意正常**”，if类型的，当点击这条，进入插件的场景设置二级页面，这部分的跳转需要怎么实现
