### ISSUE TITLE
调试本地自动化，选择条件跳转到插件自动化页后等1秒自动跳转到页面出错了

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/ios-rn-sdk#108]
已按照文档介绍配置了米家设置和插件设置，每次调试都跳转到错误页报Runtime is not ready for debugging.Make sure packager server is running，

**Comment by LiuMengzhou** [comment]
@yanmin0220 请问你问题解决了吗？没有解决的话，请再详细描述你的问题
