### ISSUE TITLE
关于打开调试模式项目失败问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/ios-rn-sdk#109]
1.按照官方文档设置如下，插件调试关闭，项目可以运行，但是无法从谷歌浏览器看到打印日志，谷歌浏览器自己不会弹出来，输入8081的地址也没有log信息。
 2.设置调试模式打开的话，谷歌浏览器会自动弹出来，但项目就运行不起来。

**Comment by LiuMengzhou** [comment]
@caojunhua 问题解决了吗？没有的话，请进一步详细描述你的问题，并贴上截图吧。

**Comment by caojunhua** [comment]
![1351541398362_ pic_hd](https://user-images.githubusercontent.com/18459414/47981033-3d0abc80-e105-11e8-9e2f-b8d665380ff2.jpg)
![1361541398362_ pic_hd](https://user-images.githubusercontent.com/18459414/47981051-48f67e80-e105-11e8-951b-cfb93bec6b5e.jpg)
![1371541398391_ pic_hd](https://user-images.githubusercontent.com/18459414/47981059-4bf16f00-e105-11e8-93e2-8f415b7b86dd.jpg)
![1381541398478_ pic_hd](https://user-images.githubusercontent.com/18459414/47981064-4eec5f80-e105-11e8-891d-c684a4bc4d78.jpg)
@LiuMengzhou 谢谢！

**Comment by LiuMengzhou** [comment]
@caojunhua 你这个app是线上4.8.9吗？
还有你外面的设置是不是把商城调试打开了。

**Comment by caojunhua** [comment]
@LiuMengzhou 商城调试地址和商城调试服务器都是关的状态。

**Comment by LiuMengzhou** [comment]
@caojunhua 你是不是最近在将插件迁移到新框架？

**Comment by caojunhua** [comment]
@LiuMengzhou 
![1421541400419_ pic_hd](https://user-images.githubusercontent.com/18459414/47982159-aa205100-e109-11e8-933f-d5c2c3ec9757.jpg)
这个我不确定。。。

**Comment by LiuMengzhou** [comment]
那你试试这样：
1. 开启插件调试
2. 用chrome打开一个**无痕**tab，然后键入：
http://localhost:8081/debugger-ui

**Comment by caojunhua** [comment]
@LiuMengzhou 谢谢你的建议，
1、我只要打开插件调试，我的项目就跑不起来。。。
2、我只有关闭插件调试，我的项目才可以跑起来，但是用chrome打开一个无痕tab，然后键入：
http://localhost:8081/debugger-ui，看到的界面是这样的

![](https://user-images.githubusercontent.com/18459414/47981059-4bf16f00-e105-11e8-93e2-8f415b7b86dd.jpg)

**Comment by LiuMengzhou** [comment]
你这个不是无痕模式吧

**Comment by caojunhua** [comment]
@LiuMengzhou 不好意思，我刚打开一个无痕tab,界面信息有所不一样，但是好像还是不行
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/18459414/47983382-1735e580-e10e-11e8-9980-1846517b68b8.png">

**Comment by LiuMengzhou** [comment]
node 服务启动了吗

**Comment by caojunhua** [comment]
@LiuMengzhou 我运行npm start了，还有别的命令吗

**Comment by LiuMengzhou** [comment]
` npm start --reset-cache`
没了。
这样吧，你给我微信，我晚上加你，空了帮你看。现在有点事

**Comment by caojunhua** [comment]
@LiuMengzhou 我的米家app版本是4.5.0的版本
![1451541408904_ pic](https://user-images.githubusercontent.com/18459414/47988533-6df6eb80-e11d-11e8-876d-fb516844549e.jpg)
![1461541408904_ pic](https://user-images.githubusercontent.com/18459414/47988540-6f281880-e11d-11e8-8f72-15572d97985d.jpg)

**Comment by caojunhua** [comment]
@LiuMengzhou 我用线上的版本v4.8.9版本试了一下，还是一样的结果。。。

**Comment by zhaolios** [comment]
和你同样的情况，请问你的问题如何解决的？
