### ISSUE TITLE
请问在此项目中如何实现css渐变效果

### ISSUE THREAD

**Issue by camilarSummer** [MiEcosystem/ios-rn-sdk#11]
因为不支持 backgroundImage:'linear-gradient(0deg,#62C292 0%,#F8CBAD 100%)'
也无法导入插件react-native-linear-gradient

**Comment by Copypeng** [comment]
请仔细阅读文档。米家 SDK 提供了 ART、SVG 这种的绘图库，可以利用他们实现各种效果。
https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/library.md
