### ISSUE TITLE
iOS在开发者模式下无法添加虚拟设备

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/ios-rn-sdk#110]
您好，在appstore和debug版本的米家app中都无法在开发者模式下创建虚拟设备，model名称和插件包名确认无误，服务器地址也是对的，电脑和手机在同一局域网内，选了创建虚拟设备后，在首页没有虚拟设备。
然后点击右上角的➕号，找到对应的产品点击后，需要配网（硬件目前还未开发，只想先把米家app扩展的UI做出来），并未弹出“当前设备model与开发者模式设置的model匹配，将与IP为xxx的调试服务器通信获取扩展程序进行调试"的信息。
希望可以得到您的回复，谢谢！

**Comment by zhuxinleibandou** [comment]
米家app:v4.8.9

![](https://img2018.cnblogs.com/blog/583948/201811/583948-20181102224736412-666735604.png)

![](https://img2018.cnblogs.com/blog/583948/201811/583948-20181102224741575-178491056.png)

**Comment by zhuxinleibandou** [comment]
具体参数如下：

调试插件model名称:
ant.hood.jjczx                    (ps:此名称是产品的model名称，对吧？)
服务器IP地址：
192.168.1.75                    (ps:这个是电脑IP，手机和电脑处于同一局域网段内，2.4g网段)
插件包名:
com.ant.hood.ios              (ps:此名是扩展app的程序包名)

目前想先做UI，控制功能等硬件出来后在调。
感谢！
期待您的回复！谢谢

**Comment by zhuxinleibandou** [comment]
dev房间下也没有。 米家appstore版本 和 beta4.5.03版本

**Comment by zhuxinleibandou** [comment]
https://img2018.cnblogs.com/blog/583948/201811/583948-20181104203026804-1654460353.png

**Comment by sofichael** [comment]
ant.hood.jjczx 是你后台配置设定的model名称
com.ant.hood.ios 是你开发项目里面定义的包名
其实做UI完全可以本地搭建框架开发，联调的话是要打通调试。

**Comment by zhuxinleibandou** [comment]
> ant.hood.jjczx 是你后台配置设定的model名称
> com.ant.hood.ios 是你开发项目里面定义的包名
> 其实做UI完全可以本地搭建框架开发，联调的话是要打通调试。

感谢回复！ 是的，ant.hood.jjczx 上后台配置的model名称，com.ant.hood.ios 是扩展的包名，就是在dev房间下没有虚拟设备 ，model需要在后台申请上线吗？ 目前没有申请上线，只把基础配置设置了

**Comment by zhuxinleibandou** [comment]
> ant.hood.jjczx 是你后台配置设定的model名称
> com.ant.hood.ios 是你开发项目里面定义的包名
> 其实做UI完全可以本地搭建框架开发，联调的话是要打通调试。

最近才接触的rn，目前先把UI做出来，可是在米家app中扩展不知道如何去运行扩展的项目了 - - 如果扩展的项目能跑起来也就不急了，火烧屁股目前就是，哈哈哈。一脸懵逼

**Comment by sofichael** [comment]
前提是要通过审核，联系米家那边的人，不需要model申请上线。

**Comment by zhuxinleibandou** [comment]
> 前提是要通过审核，联系米家那边的人，不需要model申请上线。

过审了，目前在米家app右上角的+号中 能找到对应的设备 - -好奇怪，按照文档上的去把npm开启了，也设置了开发者模式，创建虚拟设备后就是找不到 - - 
[](https://img2018.cnblogs.com/blog/583948/201811/583948-20181104204650293-1978810154.png)

**Comment by sofichael** [comment]
退出账号，杀掉app，再登陆看看，还不行，就删掉app，再尝试。

**Comment by zhuxinleibandou** [comment]
> 退出账号，杀掉app，再登陆看看，还不行，就删掉app，再尝试。

嗯 再试试 谢谢老哥！

**Comment by LiuMengzhou** [comment]
@zhuxinleibandou 不好意思，那可能还是我们APP的bug，你先借用同事的账号进行开发，毕竟开发周期紧张。
等我们改好之后给你包。

**Comment by zhuxinleibandou** [comment]
> @zhuxinleibandou 不好意思，那可能还是我们APP的bug，你先借用同事的账号进行开发，毕竟开发周期紧张。
> 等我们改好之后给你包。

好，谢谢，如果beta版本修改好 麻烦通知一下，感谢🙏

**Comment by pencilCool** [comment]
已经修好了

**Comment by zhuxinleibandou** [comment]
> 已经修好了

下载后确实可以了，谢谢🙏

**Comment by LiuMengzhou** [comment]
> > 已经修好了
> 
> 下载后确实可以了，谢谢

@zhuxinleibandou 是用的线上版4.9.1吗？
