### ISSUE TITLE
请问启动了node服务器后，如何把扩展代码运行起来？虚拟设备目前添加了没反应

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/ios-rn-sdk#111]
您好，我按照文档提示，npm start --reset-cache 启动了node服务后，手机和电脑在同一局域网内，使用米家app beta版本(4.5.0.3) 创建虚拟设备后，dev房间下没有虚拟设备。

因为开发周期紧张，想先把UI做一下，因为创建不了虚拟设备，sdk不知道如何运行，使用react-native run-ios 运行不了- - 希望可以得到您的指导，谢谢！

**Comment by zhuxinleibandou** [comment]
[](https://img2018.cnblogs.com/blog/583948/201811/583948-20181102224741575-178491056.png)
[](https://img2018.cnblogs.com/blog/583948/201811/583948-20181104203026804-1654460353.png)
[](https://img2018.cnblogs.com/blog/583948/201811/583948-20181104204650293-1978810154.png)

**Comment by LiuMengzhou** [comment]
#110 duplicate
