### ISSUE TITLE
自动化（智能）app设置问题 

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/ios-rn-sdk#112]
**环境条件**
- app版本: 米家Beta  v4.5.0 
- 相关模块和API: 
    开发自定义自动化
    MHPluginSDK. extraInfo
    MHPluginSDK.finishCustomSceneSetupWithTrigger(trigger);

**问题描述**

在“开发自定义自动化”过程中，第四部描述了获取相关数据extraInfo和value。但是没有说怎么使用，就直接跳转到完成设置后，需要调用MHPluginSDK.finishCustomSceneSetupWithTrigger(trigger)。请问app要设置些什么呢？extraInfo，payload和trigger的需要设置的数据又包含哪些？有没有相关的Demo？

**使用方法**

1、我在iot中添加了自动化设置，类别为if，填写了“扩展程序参数”，记录id
2、在开发者模式，填写相关配置，填写自定义场景id，勾选“选中-触发条件/取消-动作”
3、进入设备扩展程序，在智能模块的添加操作中，在“如果”中选中“新添加的自动化设置”，进入SceneMain.js
4、在SceneMain的componentDidMount方法中打印MHPluginSDK.extraInfo.trigger，其中trigger.value=""
5、自定义一个button，点击后代码如下：
    MHPluginSDK.extraInfo.trigger.value = 0x00000001
    MHPluginSDK.finishCustomSceneSetupWithTrigger(MHPluginSDK.extraInfo.trigger);
6、返回智能模块的添加操作，在“就执行”中选中网关设备，并进行语音播报。
7、结果，在该设备触发自动化操作后，没有相关的语音播报。求解答。

**Comment by gaopingfly** [comment]
MHPluginSDK.extraInfo.trigger.value我可用keyId也试过，还是不行。求帮助。

**Comment by LiuMengzhou** [comment]
@gaopingfly 

新建自定义条件时，你可以打印`extraInfo.trigger`看看是不是json数据结构，此时`trigger.value`也应该是空。这些都是没问题的。

至于如何给value赋值，需要和固件/后台商定数据结构以及需要传递什么数据，比如json或者字符串。给value赋值完成之后，调用`finishCustomSceneSetupWithTrigger`，传入整个`trigger`即可。客户端和云端都是将整个`trigger`作为`payload`传递。这样保证数据的自由度，易扩展。
不知道我说明白没。

**Comment by gaopingfly** [comment]
@LiuMengzhou 

感谢。已经确认问题了。我们的固件/后台的同事也是一知半解，我验证后，发现他们配置的数据有问题。哎！千错万错都是app的错。
