### ISSUE TITLE
米家app怎么创建bitmap提供给opengl使用？

### ISSUE THREAD

**Issue by ttsaite375** [MiEcosystem/ios-rn-sdk#115]
**check [docs](https://github.com/MiEcosystem/ios-rn-sdk/tree/master/MiHomePluginSDK/docs) before issue**

## Support Question

**环境条件**
- app版本: [e.g. v6.0.0/DB]
- 相关模块和API: [e.g. MHPluginSDK.saveInfo]

**问题描述**
我们现在有一款设备接入米家，需要用到opengl功能。但是需要用数据生成bitmap，没看到rn的opengl的接口有创建位图的，想着应该是米家app原生有创建bitmap接口给rn用，请问这个接口是什么？

**使用方法**

你是如何使用SDK的？
正常ios插件开发

**尝试过的解决办法**
  查找rn的opengl文档，没找到

**其他的上下文/日志/截图**

提供更多的上下文，有日志或者截图更好。

**Comment by ttsaite375** [comment]
> 请问你们使用的是rn 的opengl 中的哪一个接口，需要用到bitmap？

glTexImage2D这个，用来画纹理的

**Comment by pencilCool** [comment]
你们的原始数据是什么样式的

**Comment by ttsaite375** [comment]
> 你们的原始数据是什么样式的？

格式我邮件发了，麻烦看一下，发给汤工的

**Comment by pencilCool** [comment]
好的

**Comment by pencilCool** [comment]
图片的宽和高是多少？
