### ISSUE TITLE
请问 MHPluginSDK.openDeviceUpgradePage()这个函数如何使用？

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/ios-rn-sdk#116]
调用MHPluginSDK.openDeviceUpgradePage()后进入的页面是可以自动固件升级么？需要配置什么东西么，我看文档里只写了“分享过来的设备是无法进行固件升级的，所以此时此方法无效”，不太清楚怎么用

**Comment by LiuMengzhou** [comment]
@Android-yzhang 对，你们试试就知道了
