### ISSUE TITLE
开发者模式创建一个虚拟设备，首页设备看不到添加的

### ISSUE THREAD

**Issue by lxx123456** [MiEcosystem/ios-rn-sdk#119]
## Bug Report

**实际现象**

从小米平台下载了debuger版本的ipa，用开发者模式登陆之后，打开开发者模式，添加一个model创建一个虚拟设备之后，在米家首页我的设备跟dev里面都看不到添加的设备

**期望表现**

希望能看到用于调试的虚拟设备

**环境**
ios设备

**其他的上下文/日志/截图**
![11542183869_ pic](https://user-images.githubusercontent.com/8319702/48469423-c7e86700-e829-11e8-87e8-7bae82eb210a.jpg)

**尝试过的解决办法**

也试过设置model的ip地址改成我电脑局域网的地址也不可以

**Comment by LiuMengzhou** [comment]
@lxx123456 #110

**Comment by lxx123456** [comment]
我下载了最新版的app，按照文档的步骤试了之后还是添加不上虚拟设备到我的设备列表，我要开发调试，所以要添加一个虚拟设备到我的设备列表。

我是从这个git上下载的sdk的包，按照说明，我用createPlugin脚本创建了我们自己扩展程序的包名，然后想调试开发，但是在app我的设备列表的首页添加不上虚拟设备。还想问一下这个开发者模式开启之后，里面的model是我们在开发者平台创建的硬件的model名字，调试服务器我试过电脑的ip，也试过小米的服务器，都不可以，插件包名是扩展程序的包名，试过都不可以

**Comment by LiuMengzhou** [comment]
![demo](https://user-images.githubusercontent.com/13726966/48528299-3cbeae00-e8c9-11e8-8fab-81a0b0b553e8.gif)
@lxx123456 别慌。
1. 我们验证过，可行。
2. 需要调试的虚拟设备model，你的开发者账号具有开发权限吗？也就是谁这款设备是否在你的开发者账号所属企业开发组下。请check。
3. 开发者设置下的model必须准确无误。

**Comment by LiuMengzhou** [comment]
Duplicate of #110

**Comment by lxx123456** [comment]
我的开发者是有开发权限的，这款设备在我的开发组下，设置完model之后在首页的dev下没有这个虚拟设备的，有dev的那个tab，点击之后没有虚拟设备，我确定。设备列表里面也能搜索到我们这款设备，是不是ip地址不对或者是node服务器之类的问题啊？ip我设置的是我电脑的ip，也试过小米的服务器地址都不可以，你再帮我确定一下，麻烦再给我回复一下谢谢

**Comment by LiuMengzhou** [comment]
方便的话，开发者账号密码，设备model提供一下吧
liumengzhou@xiaomi.com

**Comment by lxx123456** [comment]
添加的虚拟设备不稳定，大部分时间在米家首页是没有dev的
