### ISSUE TITLE
ios真机调试

### ISSUE THREAD

**Issue by CGseng** [MiEcosystem/ios-rn-sdk#12]
您好，ios连接真机调试的时候在米家Bate中打开插件调试，插件无法正常进入，关闭就可正常进入，导致无法在浏览器上面调试代码，急急急！请帮忙解答一下！

**Comment by CGseng** [comment]
Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope':

**Comment by Copypeng** [comment]
插件无法正确进入只有一个原因：开发者模式中的配置不正确，请检查 ip 地址与插件包名，同时保证真机和调试电脑在同一个局域网。
