### ISSUE TITLE
getAvailableFirmwareForDids接口返回值为 true，null，固件升级获取不到新版本

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/ios-rn-sdk#120]
硬件开发已经提交了新的固件版本，android能发现新的版本，但是iOS端一致显示当前是最新版本，did是blt.3.tg3aih5c8g00，使用MHPluginSDK.openDeviceUpgradePage();也显示当前是最新版本

**Comment by Copypeng** [comment]
从 did 看应该是蓝牙设备。蓝牙设备因为是本地 OTA，即插件自行与设备通讯完成。你使用的接口并不适用，蓝牙设备的OTA流程参考专门的引导章节。https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/blernfirmwareupdate.md
