### ISSUE TITLE
关于数据库realm的使用出现的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/ios-rn-sdk#124]
您好，我这边使用数据库realm出现了一些问题：
1.我先按照步骤导入realm
![image](https://user-images.githubusercontent.com/18459414/49078851-165e2280-f27a-11e8-8c29-3eeca3548be8.png)
2.新建一个MyRealm文件
![image](https://user-images.githubusercontent.com/18459414/49078904-3beb2c00-f27a-11e8-9605-7f6ec1f86906.png)
3.运行报错
![image](https://user-images.githubusercontent.com/18459414/49078916-486f8480-f27a-11e8-8c9e-ce7f4b7a2c63.png)
4.根据错误提示寻找解决方法
![image](https://user-images.githubusercontent.com/18459414/49078935-51f8ec80-f27a-11e8-8f2f-eabd1e3c518d.png)
5.并没有找到解决办法

**Comment by Copypeng** [comment]
Realm 这个库是不是不是纯 JS 的，需要在工程中打入二进制库？

**Comment by caojunhua** [comment]
不知道，是数据库来着，我自己写的一个测试demo可以用，在我们的米家扩展程序项目里不能用。。。

**Comment by Copypeng** [comment]
https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/library.md

**Comment by caojunhua** [comment]
用什么本地数据比较合适？我看了一下，没看到有数据库。
