### ISSUE TITLE
MHXiaomiBLE.oneTimePassword 一次性密码接口疑问

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/ios-rn-sdk#125]
**check [docs](https://github.com/MiEcosystem/ios-rn-sdk/tree/master/MiHomePluginSDK/docs) before issue**

## Support Question

**环境条件**
- app版本: [e.g. v4.8.9/DB]
- 相关模块和API: [e.g. MHXiaomiBLE.oneTimePassword]

**问题描述**

1.interval，这个时间间隔的单位是不是是分钟，注释写的秒，实测传入30，30分钟内获取到的密码组是一样的

**interval，时间间隔，单位为秒，类型为 number，传入 1 到 60 的整数**

2.生成的密码组的生效时段的规则是怎么样的，例如 12：27分我创建一组30分钟间隔的密码，这8个密码是生效至12：57，还是说12：50

**使用方法**

```
MHXiaomiBLE.oneTimePassword(30,  8, (error,passwds)=>{
    if(!error){
        //parse passwds array
	}
});

```

**尝试过的解决办法**

**其他的上下文/日志/截图**

提供更多的上下文，有日志或者截图更好。

**Comment by Copypeng** [comment]
抱歉，重新更新了文档。之前文档有误，开发者只需输入有效期，单位为分钟，以及密码位数即可。当前时间 UTC，单位为秒，由米家App处理并保证准确性。

**Comment by damiknows** [comment]
O(∩_∩)O谢谢
