### ISSUE TITLE
引入ART模块，运用其中的LinearGradient，代码如下，但也没无任何颜色效果，包括边框效果均未出现，也无报错，页面正常打开，求解惑

### ISSUE THREAD

**Issue by camilarSummer** [MiEcosystem/ios-rn-sdk#13]
'use strict';

var React = require('react-native');
var {
  StyleSheet,
  WebView,
  View,
  Text,
  StatusBar,
  Platform,
  Navigator,
  ART,
  Dimensions,
} = React;

var {
    Surface,
    Shape,
    Path,
    LinearGradient,
    RadialGradient
} = ART;

var {
    width,
    height
} = Dimensions.get('window');

var Rectangle = require('./Rectangle.art');

import Circle from '../CommonModules/Chart/Circle';

class DataDisplay extends React.Component {
  render() {

      var textHeight = 20;
      var surfaceHeight = (height - (Platform.OS === 'ios' ? 64 : 76) - 2*textHeight)/2;
      return (
          <View style={styles.container} >
              <StatusBar barStyle='light-content'/>
              <View style={{width:width, height:textHeight}}><Text style={{textAlign:'center'}}>线性渐变</Text></View>
              <Surface width={width} height={surfaceHeight}>
                  <Rectangle x={width/2-50} y={20} width={100}
                             height={200}
                             stroke="red"
                             strokeWidth={1}
                             fill={
                                 new LinearGradient({
                                         '0': 'rgba(255,0,0,0)', //stop offsets and color
                                         '0.5':'rgba(0,255,255,1)',
                                         '1':'rgba(0,0,255,1)'
                                     },
                                     "50",  //x1 起始点x
                                     "0",  //y1 起始点y
                                     "50",  //x2 结束点x
                                     "200"  //y2 结束点y
                                 )}/>
              </Surface>
          </View>
      );

  }
}

var styles = StyleSheet.create({
    container: {
        marginTop: Platform.OS === 'ios' ? 64 : 76,
        flexDirection:'row',
        flex:1,
    }

});

var route = {
  key: 'DataDisplay',
  title: '数据展示',
  component: DataDisplay,
  sceneConig: {
    ...Navigator.SceneConfigs.FloatFromRight,
    gestures: {}, 
  }
};

module.exports = {
  component: DataDisplay,
  route: route,
}

**Comment by camilarSummer** [comment]
return (
          <View style={styles.container} >
              <Text>线性展示</Text>
              <Surface width={100} height={100}>
                  <Shape
                      x={width/2-50} y={20} width={100}
                      height={100}
                      stroke="red"
                      strokeWidth={1}
                      fill= '#000000'/>
              </Surface>
              <Text>线性展示</Text>
          </View>
      );


代码简略，但依然不出现任何颜色，
另请问在SDK中开发，有类似于开发者工具一样的方式进行页面布局查看吗？

**Comment by Copypeng** [comment]
你好，没有 Xcode 中的页面布局查看，可以使用 Chrome 开发调试可能会更方便。

我们没有精力帮助开发者首先具体业务功能与动效。关于 ART，可以参考一下入门教程，比如：

https://blog.wytiny.com/2017/02/16/react-native-art/

https://medium.com/the-react-native-log/animated-charts-in-react-native-using-d3-and-art-21cd9ccf6c58
