### ISSUE TITLE
获取不到蓝牙的服务和特征值

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/ios-rn-sdk#130]
react-native版本 0.54.4

1.可以获取到mac地址，但是获取不到服务值
部分代码截图
![image](https://user-images.githubusercontent.com/18459414/49719721-eca0f480-fc98-11e8-875d-61ee372d05e6.png)
对应打印结果截图
![image](https://user-images.githubusercontent.com/18459414/49719734-fa567a00-fc98-11e8-9227-5ac2f8b42893.png)

2.可以连接成功，但是打印的mac地址，和isConnected的布尔值的时候，显示undefined
部分代码截图
![image](https://user-images.githubusercontent.com/18459414/49719830-38ec3480-fc99-11e8-8585-80e25e09f389.png)
对应打印截图

![image](https://user-images.githubusercontent.com/18459414/49719946-9c766200-fc99-11e8-9ec8-02b717d1b493.png)

对于这个问题，我不知道是怎么回事，想请教一下你们这边的小伙伴们，谢谢！

**Comment by Copypeng** [comment]
已转到 https://github.com/MiEcosystem/miot-plugin-sdk/issues/134
