### ISSUE TITLE
MHXiaomiBLE.oneTimePassword 生成密码组与固件生成不符

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/ios-rn-sdk#132]
## Bug Report

**实际现象**
调用MHXiaomiBLE.oneTimePassword 得到的8个一次性密码与固件生成的不符，无法正常开锁。

**期望表现**

生成的一次性密码组与固件安卓一致，可以正常开锁

**环境**
- app版本: [e.g. v4.8.9/db build751]
- 相关模块和API: [e.g. MHXiaomiBLE.oneTimePassword]

**复现步骤**
1. 打开门锁插件-设置-临时密码-一次性密码
2. 点击添加密码得到8个一次性密码组
3. 与嵌入式生成的核对，两者不相符

**其他的上下文/日志/截图**

```

 MHXiaomiBLE.oneTimePassword(10,  6, (error,passwds)=>{

     if(!error){
        console.log("一次性密码：",passwds);
     }
  });

```

15：01

* iOS生成的密码组： (8) [715981, 565450, 655509, 149383, 37274, 624092, 838101, 642112]

* Android生成的密码组：  
 0 = 52366
 1 = 184576
 2 = 432185
 3 = 693674
 4 = 669048
 5 = 167598
 6 = 8407
 7 = 616192

* 固件生成的密码组：  
pwd 0: 2790052366
pwd 1: 1980184576
pwd 2: 1138432185
pwd 3: 131693674
pwd 4: 1671669048
pwd 5: 3011167598
pwd 6: 2209008407
pwd 7: 3268616192

(固件取后6位，APP都是生成6位密码)

**尝试过的解决办法**

<!-- 请添加准确的label>

**Comment by Copypeng** [comment]
出现一次性密码无法开锁时，此时 App 能正常连接上锁嘛？

**Comment by damiknows** [comment]
@Copypeng 我用自己调试的手机重新删除门锁，再添加还是会有同样的问题

**Comment by Copypeng** [comment]
你们的设备需要单独支持，已经加上。
