### ISSUE TITLE
蓝牙发送写数据的请求的报错提示信息

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/ios-rn-sdk#134]
参照这个文档写的发送数据给蓝牙硬件
![image](https://user-images.githubusercontent.com/18459414/49794714-33fbb380-fd73-11e8-8a5c-0e5d6f048c84.png)
但是这个写法有错误，因为setNotify返回的还是本接口，如果按照文档的写法会报错找不到read和write方法
![image](https://user-images.githubusercontent.com/18459414/49794788-5ee60780-fd73-11e8-875f-2de0ef872260.png)
所以改成了这样的写法不会报错，
![image](https://user-images.githubusercontent.com/18459414/49794939-bab09080-fd73-11e8-9f8c-e4529ea3f41b.png)

但是在调试过程中发现报错信息如下
![snip20181211_3](https://user-images.githubusercontent.com/18459414/49795124-27c42600-fd74-11e8-8b5b-e0c1cf0b2475.png)
不明白这是什么原因，麻烦小伙伴们帮忙看看！谢谢！

**Comment by Copypeng** [comment]
提到新框架那个项目上吧。
