### ISSUE TITLE
ios包名修改求助

### ISSUE THREAD

**Issue by xfce** [MiEcosystem/ios-rn-sdk#137]
您好，我们在开发一款产品的ios扩展程序，前期开发失误，包名命名错误，现在确认包名错误导致不能正常开发，发过邮件请求修改包名，但还没有响应。扩展程序id 1226， 包名帮忙修改为 com.pwzn.relaysswrevb.ios， 谢谢

**Comment by LiuMengzhou** [comment]
> 您好，我们在开发一款产品的ios扩展程序，前期开发失误，包名命名错误，现在确认包名错误导致不能正常开发，发过邮件请求修改包名，但还没有响应。扩展程序id 1226， 包名帮忙修改为 com.pwzn.relaysswrevb.ios， 谢谢

1. 包名命名错误是指？
2. 为什么包名错误导致不能正常开发？
3. 📧邮件发给了谁？

**Comment by xfce** [comment]
@LiuMengzhou 你好
1）ios的扩展程序包名目前使用的是pwzn.switch.revb.ios(扩展程序ID 1226) ;
2）使用目前的包名，发现订阅消息，没有响应，然后我们搞了个零时C版本com.pwzn.relaysswrevc.ios 所用功能都正常了，因为我们前期已经做完了好多工作，就差ios这块了，所以想请平台帮忙把我们b版本的包名改成com.pwzn.relaysswrevb.ios ;
3）邮件发个平台提供的 miot-openhome@xiaomi.com 。发过几封了，还没回应

**Comment by xfce** [comment]
@LiuMengzhou 感谢，改好了
