### ISSUE TITLE
判断蓝牙网关是否连接接口问题

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/ios-rn-sdk#138]
## Bug Report

**实际现象**

isBtGateWaySubDeviceWithMac 判断小米米家智能门锁与蓝牙网关是否连接接口，如果进入插件时手机蓝牙是关闭的，那么接口返回的一定是未连接的，这个时候把蓝牙打开或者打开后瞬间关闭再去请求，接口返回的是已连接；手机蓝牙打开时距离门锁很远的地方进入插件，接口返回的也是已连接的

**期望表现**

手机蓝牙是否打开不影响接口判断门锁与蓝牙网关是否连接返回结果

**环境**
- app版本: [e.g. v4.10.2/app store]
- 相关模块和API: [e.g. MHPluginSDK.isBtGateWaySubDeviceWithMac]

**复现步骤**

以下所有情况基于门锁已经连接上蓝牙网关：

情况一：在门锁附近
1. 关闭手机蓝牙，进入插件 -----> 这个时候调用返回未连接
2. 基于步骤1，打开蓝牙，然后立马关闭 -----> 这个时候调用返回已连接

情况二：距离门锁很远（确保门锁无法直连）
1. 关闭手机蓝牙，进入插件 -----> 这个时候调用返回未连接
2. 基于步骤1，打开蓝牙然后立马关闭或打开蓝牙并保持打开 -----> 这个时候调用返回已连接

情况三：距离门锁很远（确保门锁无法直连）
1. 打开手机蓝牙，进入插件 -----> 这个时候调用返回已连接

**其他的上下文/日志/截图**

![image](https://user-images.githubusercontent.com/41932871/50418598-4abc0300-0867-11e9-8d94-cd7ff54f781a.png)

**尝试过的解决办法**

<!-- 请添加准确的label>

**Comment by damiknows** [comment]
补充调用代码如下

```

 // 获取蓝牙网关的状态
    getBleGateWayConnectStatus () {
      //是否连接BLE网关
      MHPluginSDK.isBtGateWaySubDeviceWithMac(MHLockManager.lockDevice.mac,(res)=>{
        console.log('蓝牙网关是否连接：'+ res)
        if(!res){
          isLoadingServerData = false
          // 未连接
          this.setLockStatus('bluetoothUnConnected_unConnect')
          this.getServerDoorStatusDetection(true)
        } else {
          // 已连接
          this.getServerDoorStatusDetection()
        }
        // this.getServerDoorStatusDetection()
      });

    }

```

**Comment by pencilCool** [comment]
你好，我们这测完之后，并没有复现问题：
手机蓝牙是否打开不影响isBtGateWaySubDeviceWithMac这个接口的返回结果

**Comment by qinliduan** [comment]
> 你好，我们这测完之后，并没有复现问题。
> 
> 手机蓝牙是否打开不影响isBtGateWaySubDeviceWithMac这个接口的返回结果。
> 和预期结果一致。

您好，刚刚又验证了一下，问题依然存在，我们这边的测试、用户都反馈这问题；我们这边这个问题是必现的，是否需要我们提供其他的信息？

**Comment by Copypeng** [comment]
开发者可以补充一下造成这种现象的根源在哪。

**Comment by qinliduan** [comment]
> 开发者可以补充一下造成这种现象的根源在哪。

我们拿到mac地址之后赋值在插件基类，使用时默认已经赋完值了，但是这个赋值过程是在直连时去做的，蓝牙关闭后没有走直连逻辑，所以mac地址为空的，我们开发调试的时候基本都是打开过蓝牙的，查看mac地址也都是有的，所以当后面遇到问题，排查问题的时候忽略了检查调用接口输入的mac地址，只关注返回结果了。建议接口可以对明显的非法mac地址做一下判断，返回错误提示。由于我们的疏忽，浪费大家的时间，是在是抱歉
