### ISSUE TITLE
如何在更多菜单中添加设备联网信息的选项？

### ISSUE THREAD

**Issue by icedu8910** [MiEcosystem/ios-rn-sdk#139]
**check [docs](https://github.com/MiEcosystem/ios-rn-sdk/tree/master/MiHomePluginSDK/docs) before issue**

## Support Question

**环境条件**
- app版本: [e.g. v6.0.0/DB]
- 相关模块和API: [e.g. MHPluginSDK.saveInfo]

**问题描述**

我们希望能在更多菜单中显示设备的联网信息，以方便用户能够实时了解自己设备的运行情况。

我们在MHSetting.js文件中添加了相应的选项卡，但在MHPluginSDK说明文档中，未能找到相应的接口对象。

**使用方法**

你是如何使用SDK的？

**尝试过的解决办法**

**其他的上下文/日志/截图**

提供更多的上下文，有日志或者截图更好。

**Comment by LiuMengzhou** [comment]
@icedu8910 类似与安卓插件通用设置里面的吗？

**Comment by icedu8910** [comment]
@LiuMengzhou 
安卓客户端中，通用设置下的“网络信息”。
![_20190102173631](https://user-images.githubusercontent.com/45703834/50586616-33a79180-0eb5-11e9-86a1-c2a042142a90.jpg)

**Comment by LiuMengzhou** [comment]
目前iOS没有现成的查看网络信息的接口提供给插件，这个我们评估之后后续给出。

**Comment by icedu8910** [comment]
你好，为何小米摄像头已经提供了这一项 功能呢？
