### ISSUE TITLE
registerXiaoMiBLE报错，错误code为3

### ISSUE THREAD

**Issue by oladevelope** [MiEcosystem/ios-rn-sdk#142]
设备刚刚添加完成，进入扩展程序后，调用registerXiaoMiBLE，报错。错误code为3

**Comment by Copypeng** [comment]
这个 API 不要调用，厂商用不上，后续会废弃。设备添加完成，即已经完成register过程。

跟设备建立连接使用 loginXiaoMiBLE

**Comment by oladevelope** [comment]
好的，谢谢
