### ISSUE TITLE
米家连接蓝牙设备，频繁出现不能连接的情况

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/ios-rn-sdk#158]
**实际现象**

近两天发现打开米家ios，连接蓝牙设备，频繁出现连接失败的情况。

**环境**
- app版本: 4.12.0
- 相关模块和API: 1115

怀疑是米家后台更新，对旧设备支持有问题。我们在没有主动更新米家应用，和插件的情况下，从2019年2月21日，发现连接异常的问题。发现问题后，想开启调试，发现米家APP已经不能调试旧版插件。从小米开发者平台，下载米家APP，发现可以正常连接设备。

**Comment by blockdate** [comment]
希望跟你确认下问题，
1. 蓝牙连接异常的app版本是* 4.12.0吗，2/21我们发布了版本4.13.（旧版本app应该是可以直接调试旧插件，新版本APP可以在开发者设置中勾选 使用旧插件 进行旧插件debug）
2. 使用米家4.13会有连接异常问题吗。
3. 从开发者平台下载的米家APP版本号和beta number是多少呢。

**Comment by Android-yzhang** [comment]
旧版的已经卸载了，不过我没有在App Store上更新过。但是旧版上，原先是有开发者模式，商城调试地址，商城调试服务器，开发者通用设置，4个选项，昨天我打开app的时候只有2个选项（开发者模式，开发者通用设置），并且开发者通用设置中，没有插件调试选项， 打开开发者模式输入model等信息后，发现提示的是找不到新的插件

**Comment by Android-yzhang** [comment]
使用米家4.13，使用旧版插件不能正常工作，并且开启开发者模式，可以进入旧版插件，但是所有资源文件会按照新版插件的位置去找，所以找不到资源文件。
并且新版APP，调试旧版插件无法调试程序，没有找到原先在通用设置里的插件调试。
从开发者平台下载的米家APP版本号是4.12.0，图标上写的是831.

**Comment by Android-yzhang** [comment]
@blockdate 应该是iPhone开了app自动更新了，所以昨天用的就是新版的app

**Comment by blockdate** [comment]
开发者模式目前确实存在测试环境下资源文件的问题。

方便加一下微信吧，发送到wulei7@xiaomi.com，这个问题如果确实存在，那得尽快解决。

**Comment by blockdate** [comment]
沟通后确定解决方案为：直接discoverCharacteristics会有错误，正确操作流程采取先discoverService再discoverCharacteristics。
