### ISSUE TITLE
调试com.xiaomi.demoios全程记录

### ISSUE THREAD

**Issue by schillerGao** [MiEcosystem/ios-rn-sdk#16]
调试ios-rn-sdk-master 小米demo：com.xiaomi.demoios

1. npm install 
   切记，这一步一定要npm install ，cnpm有很多问题。
2. 打开ios-rn-sdk-master/MiHomePluginSDK文件夹
3. 使用个人小米开发者账号登录米家App
   使用个人开发者登录该米家App后，会出现开发者模式一栏。足见小米野心所在。
4. 在开发者模式一栏中填入一下信息
   调试model名称：xiaomi.demo.v1 （先不加com）
   调试服务器IP：192.168.31.110，不用输入端口号，默认8081，确保手机米家App和电脑在同一wifi下。
5. 插件包名：com.xiaomi.demoios（使用这个该SDK提供的demo 包）
6. 自定义场景id：没有就不填，选填
7. 勾选创建一个虚拟设备，其他的可以不用勾选。
8. 确认后返回首页并下拉刷新首页，出现Dev栏，然后点击Dev
9. 出现报错：不要慌，重新到回到4，修改model名为：com.xiaomi.demo.v1，加上com（我怀疑这个bug是插件工程师在做校验的时候不一致导致的，这就坑我们这些生态企业了！）
10. 再次回到首页，点击dev，会出现虚拟设备，然后点进去就可以看到该sdk提供的虚拟设备的UI了。
11. 只想说一句，米家App在App Store上评分2.2也不是没有道理的，对开发者不友好，对用户也不友好。建议产品经理理清楚整个软件的思路，现在是控制的基础功能没做好，设备太多，没顾得所有。智能场景太复杂，联动没想好，RN化之后一堆待解决问题。
12. over

**Comment by Copypeng** [comment]
感谢反馈，我们会提高文档可读性，降低开发门槛。

1，我们文档中明确使用的是 npm，你既然自己用了其他工具，就需要自己承担负担风险，了解他们的不同，解决相关问题。我们暂时不对其他工具支持。

2，开发者模式下 model 没有本地校验，也无从校验，生态链公司产品的 model 可以是任何值，加不加com 跟你这个失败没有关系。作为生态链企业，生产硬件产品，请先接入 iot 平台，填入自己的产品 model 开发，如果没有成型产品，可以使用开发板，如果开发板都没有，可以尝试先创建虚拟设备，再测试，不过由于没有硬件，只能调试 UI 相关的功能。虚拟设备的 model 请使用自己在 iot 平台注册并审核通过的 model，避免跟其他产品 model 重名的可能性。

3，鉴于我并没有查询到你邮件中标识的名为 yirimao.com 的生态链公司，邮件不回复。后续有开发上的问题，请通过项目对接的 PM 反馈。

4，鉴于该 issue 的描述有很多情感词汇和自我猜想，与该项目无关。关闭该 issue。

对开发者造成的困扰很抱歉，我们会努力提高文档可读性和降低开发门槛。
