### ISSUE TITLE
蓝牙绑定的时候iOS APP下发0x00000001，导致插件出现code=2并退出绑定

### ISSUE THREAD

**Issue by codebeautiful** [MiEcosystem/ios-rn-sdk#162]
## Bug Report

**实际现象**

用iOS绑定蓝牙设备的时候，APP显示code=2并退出。
蓝牙设备端米家库打印：
[W] mi srv: Connected Peer MAC:
29 A3 A3 62 DF 68                                )??b?h          
[I] mi srv: default interval min: 24, max: 24
[I] mi srv: update interval max: 24, min: 24
[W] mi srv: NON-START OPCODE 0x00000001
[W] mi srv: Disconnect reason 13.
表示APP下发0x00000001并立即断开连接。 而正常情况下是下发0x00000110，启动绑定流程

同一个蓝牙设备，用Android绑定，没有这个问题

**期望表现**

和正常流程一样

**环境**
- iOS app版本: [e.g. v4.14.101/db]
- iOS app store版本:[e.g. v4.13.101]
- Android 版本:[v5.4.61]

**复现步骤**
正常的绑定流程

**其他的上下文/日志/截图**
·
![IMG_0674](https://user-images.githubusercontent.com/7651192/54730374-8b57be00-4bc3-11e9-8730-a75423abc1e0.jpeg)

**Comment by Copypeng** [comment]
应该是设备广播问题，设备广播中没有标识Capability。
