### ISSUE TITLE
应小米测试要求，首次进入插件，要显示用户协议，安卓有方法调用，iOS 有没有？

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [MiEcosystem/ios-rn-sdk#163]
![Screen Shot 2019-03-22 at 2 53 15 PM](https://user-images.githubusercontent.com/1797012/54805592-62622680-4cb2-11e9-9d64-db08bf0fbe58.png)

**Comment by Smart-XiaoLeiGe** [comment]
![image001](https://user-images.githubusercontent.com/1797012/54890592-07644580-4ee5-11e9-8929-721ae9717e1d.png)

**Comment by Smart-XiaoLeiGe** [comment]
@chundong @kyou @kangkai @jxfengzi

**Comment by Smart-XiaoLeiGe** [comment]
两个API 介绍一样，功能不一样，这文档写的可以的👎
#### *openPrivacyLicense* `AL-[129,)` 

>
>  @param license  软件许可以及使用协议的名称
>
>  @param licenseURL 软件许可以及使用协议的详细内容 的url 
>
>  @param policy 用户隐私协议的名称
>
>  @param policyURL  用户隐私协议的详细url
>
>  @param callBack   callback 
>
```
  MHPluginSDK.openPrivacyLicense("license","licenseURL","policy, "policyURL,(result)=>{
    if(result == "ok") {

    } else {
      
    }
  })
```

#### *privacyAndProtocolReview* `AL-[133,)` 

>  用于查看隐私协议和用户使用条款，参数说明
>
>  license  软件许可以及使用协议的名称
>
>  licenseURL 软件许可以及使用协议的详细内容 的url 
>
>  policy 用户隐私协议的名称
>
>  policyURL  用户隐私协议的详细url
>

**Comment by ldezho** [comment]
@Smart-XiaoLeiGe 我这边调用MHPluginSDK.openPrivacyLicense后，插件页首先白屏，然后米家app直接crash，请问您是怎么调用的？有出现过这种问题的吗？谢谢。

**Comment by Smart-XiaoLeiGe** [comment]
> @Smart-XiaoLeiGe 我这边调用MHPluginSDK.openPrivacyLicense后，插件页首先白屏，然后米家app直接crash，请问您是怎么调用的？有出现过这种问题的吗？谢谢。

就是正常的文档里面的写法
MHPluginSDK.openPrivacyLicense(LocalizedStrings.alertLicense, this.props.app.pathForResource("xxxx.html"), LocalizedStrings.alertPolicy, this.props.app.pathForResource("xxx.html"), (result) => {
                      
                    });
