### ISSUE TITLE
调试模式进入不了智能页面

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/ios-rn-sdk#165]
## Bug Report

**实际现象**

智能->右上角+号->选中设备->任意开锁（和调试配置的sc_id一样）
执行上述步骤后，页面立即crash，如图：
![IMG_0011](https://user-images.githubusercontent.com/12531667/55064154-76dc5f80-50b4-11e9-8867-04426ae85cca.PNG)

**期望表现**

期望可以进入智能页面

**环境**
- app版本: [e.g. v6.0.0/db] v4.14.101
- 相关模块和API: [e.g. MHPluginSDK.saveInfo]

**复现步骤**
1. xxx
2. xxx
3. xxx

**其他的上下文/日志/截图**

提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**

<!-- 请添加准确的label>

**Comment by fosen** [comment]
@Copypeng  你好 这个问题怎么解决，我这今天调试的时候也遇到了

**Comment by ldezho** [comment]
可以看下config.plist文件是否配置了sc_id
