### ISSUE TITLE
添加supportIPhoneX字段会使插件无法隐藏APP的导航栏吗?

### ISSUE THREAD

**Issue by LarrySue** [MiEcosystem/ios-rn-sdk#2]
app.setIsNavigationBarHidden()
和
route = {
  isNavigationBarHidden: true,
}
均不起作用

**Comment by Copypeng** [comment]
@LarrySue Hi，我 review 了跟supportIPhoneX字段相关的代码，并不会对导航有任何直接的修改。可能是连带问题。请对比  com.xiaomi.bledemo.ios 中的代码，适配了 iPhone X 且不会出现多导航的问题。

此外，能否提供 config.plist 中 pluginStructureVersion 字段的值，帮助我们定位问题。

**Comment by LarrySue** [comment]
pluginStructureVersion值为1

**Comment by Copypeng** [comment]
那可能是有这个问题了，2.x 后 SDK 固定的 pluginStructureVersion 就是 2 了，你们可以通过修改这个值，使用新导航结构来适配。新导航结构也更自由，支持更多定制。

pluginStructureVersion 值为 1 的导航，我们稍后评估兼容方案。

**Comment by Copypeng** [comment]
同时，迁移插件结构，即 pluginStructureVersion 升级为 2，最好使用 SDK 中提供的 createPlugin 脚本重新生成插件目录，以免出现目录结构不同导致的 bug
