### ISSUE TITLE
characteristic uuid 安卓和设备交互是可以的，iOS这边却提示没有。

### ISSUE THREAD

**Issue by zyh427** [MiEcosystem/ios-rn-sdk#20]
iOS这边一个新的报错问题。
下面这个characteristic uuid 安卓和设备交互是可以的，iOS这边却提示没有。

报错："not found device with characteristic uuid 524F534E-4553-5F47-5F45-49585F4E5558 on service uuid FEFE5245-5652-4553-5F45-49585F4E5558 on peripheral with identifier B2CBF943-5309-4D39-A6FA-E2C6B211683B "

**Comment by Copypeng** [comment]
需要进行 service 与 characteristic 的发现；补充蓝牙相关知识。
