### ISSUE TITLE
有关device token问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/ios-rn-sdk#21]
请问后期是否可以提供获取标识设备生命周期内（从设备快连到删除）的device token的接口？现在安卓端是可以获取到。

**Comment by Copypeng** [comment]
所谓"token"有很多，用途不尽相同。

1，请问扩展程序获取设备的 "token" 的用途是？
2，请提供一下安卓的接口名称。

**Comment by Copypeng** [comment]
不活跃。

**Comment by TheWalkingDead1024** [comment]
不好意思，很长时间没有来看这个issue。
1、token用途是用来标识设备生命周期内（从设备快连到删除）的唯一标识符，问题中已经有描述。
2、安卓设备类（BaseDevice）的数据成员mDevicestat（类名DeviceStat），在mDevicestat中有token这个属性。

**Comment by Copypeng** [comment]
已经提供 servicetoken 接口，看是否满足你们的需求。

**Comment by TheWalkingDead1024** [comment]
你好，我们想要的devicetoken可以理解为iOS程序的UUID。servicetoken不能满足此需求，而且servicetoken有时效性，且只满足小爱音箱域名的。

**Comment by Copypeng** [comment]
我跟安卓同事沟通，了解了。如下

1，token直接暴露比较危险，他们会慢慢废弃这个接口，你们可以使用tokenMD5()来唯一标示。

2，iOS会将token加密后导出，同样能满足你们唯一标示设备的需求，但是不直接暴露token。导出后我通过此issue 通知你，也请关注文档变动。

**Comment by Copypeng** [comment]
api level 140 已经支持 deviceToken() 接口。
