### ISSUE TITLE
IOS扩展程序订阅机制不好用的问题---帮忙看下，谢谢

### ISSUE THREAD

**Issue by gaoyuLumileds** [MiEcosystem/ios-rn-sdk#25]
根据贵司的文档，我们编写测试程序，步骤分别如下

1. 模块端编写指令&通过调试工具获取信息如下图

<img width="967" alt="image004" src="https://user-images.githubusercontent.com/40253816/41387441-720404b8-6fb9-11e8-8fe6-f0dba5701792.png">
<img width="1252" alt="image002" src="https://user-images.githubusercontent.com/40253816/41387512-dc673f28-6fb9-11e8-9d82-1d5622c5661b.png">

2.IOS扩展程序config.plist&reactNative代码分别如下
<img width="1011" alt="image001" src="https://user-images.githubusercontent.com/40253816/41387580-2c088bb8-6fba-11e8-98e8-afe16e7aefb0.png">
```
   MHPluginSDK.registerDeviceStatusProps(["prop.AQI","event.SentAlarm"]);
var subscription3 = DeviceEventEmitter.addListener(MHPluginSDK.deviceStatusUpdatedEventName,(notification) => {
    console.log("小米插件notification-----"+JSON.stringify(notification));
});

var subscription2 = DeviceEventEmitter.addListener(MHPluginSDK.onReceivingForegroundPushEventName,(notification) => {
    // 插件在前台收到push通知回调
    console.log(JSON.stringify(notification));
});
```
3. 结果是监听不到任何事件？这是为什么？希望小米同学可以帮忙看看我们开发的问题所在，拜托了

**Comment by Copypeng** [comment]
我们更新了更详细的文档说明，请参考 deviceStatusUpdatedEventName 常量下的示例操作。

若依然不行请排除设备端的问题。

**Comment by Copypeng** [comment]
不活跃。
