### ISSUE TITLE
使用MHPluginFS类的过程中存储再读取出来的内容为BASE64字符串，参考其他Base64解码后数据不一致了

### ISSUE THREAD

**Issue by zhusongyu** [MiEcosystem/ios-rn-sdk#26]
使用MHPluginFS类的过程中，遇到了如下问题，
1 MHPluginFS.downloadFile
2 MHPluginFS.readFileToBase64(result.filename, (success, base64Content) => {}
这样存储再读取出来的内容为BASE64字符串, 打印如下
cFGq/6TrAAAVG/p3MS4xLjBfMDAwMwD//////9Rc/FkA/////////////////////////////////////////2gA/Qe9BfwHxQX8

3 参考https://www.cnblogs.com/ryans/p/6512631.html，
进行了BASE64解码，最后还原成Byte数组，再转16进制字符串打印如下：
7051eabfa4eb8080151beab7b12e312e305f3030303300efbfbfefbf945cec9980efbfbfefbfbfefbfbfefbfbfefbfbfefbfbfefbfbfefbfbfefbfbfefbfbfefa880ed87bd05ec878505ec8080

问题是这样解码出来的数据和原数据有不一致，真实数据的16进制字符串内容如下：
7051aaffe8e6000075b7fa86312e312e305f3030303700ffffffffffb08d1b5b00ffffffffffffffffffffffffffffffffff

麻烦问下是否是我参考的BASE64解码有问题？

**Comment by LiuMengzhou** [comment]
很高兴你提出这个问题，请问你可以把BASE64解码后的中间结果贴出来吗？以及你使用的哪两个方法将解码后的字符串还原成Byte数组，再转16进制字符串？

**Comment by zhusongyu** [comment]
@LiuMengzhou 谢谢你的回复，中间过程如下：

**Comment by LiuMengzhou** [comment]
我测试了一下，这个Base64的encode和decode是没问题的，表现和MHPluginFS的Base64编解码一样。要不你再看看有没有可能是其他环节出了问题？


```js
  _test() {
    let str = "I love Xiaomi";
    MHPluginFS.writeFile("test", str, (isSuccess) => {
      console.log(isSuccess);
    })
    MHPluginFS.readFileToBase64("test", (isSuccess, base64Content) => {
      console.log(isSuccess);
      console.log(base64Content);
    })
    MHPluginFS.readFile("test", (isSuccess, utf8Content) => {
      console.log(isSuccess);
      console.log(utf8Content);
    })
  }
```

![image](https://user-images.githubusercontent.com/13726966/41659313-8408b728-74cb-11e8-9184-539a060858f6.png)

![image](https://user-images.githubusercontent.com/13726966/41659329-8d09b6ce-74cb-11e8-8c33-e1bc3abd7ba5.png)

![image](https://user-images.githubusercontent.com/13726966/41659349-9e2cd738-74cb-11e8-838e-1c3dfee6c6b9.png)

**Comment by zhusongyu** [comment]
@LiuMengzhou  我是用的下载接口保存文件的。

**Comment by zhusongyu** [comment]
@LiuMengzhou  另外，当我下载文件后用MHPluginFS.readFile接口时，读取失败。
// 下载文件后读取
        var url = 'http://cdn.cnbj0.fds.api.mi-img.com/miio_fw/048971255a04cbd33624172d00f8aedd_upd_xiaoxun.ro_skates.v1.bin?GalaxyAccessKeyId=5721718224520&Expires=1535425409000&Signature=9CZtMYHwYEXt3knVoK9pNS1KoPU=';
        MHPluginFS.downloadFile(url, "test.zip", (success, result) => {
            if (success && result.path) {
                MHPluginFS.readFile(result.filename, (success, utf8Content) => {
                    console.log(success);
                    console.log(utf8Content);
                    if (success) {
                        //
                    }
                });
            }
        });

结果：false
          null

**Comment by LiuMengzhou** [comment]
@zhusongyu 你好。我试了一下readFile，确实读取失败。用readFileToBase64读取没问题，但是我没办法打开你给的链接中下载的bin，所以无法比较是否一致。

@Copypeng 烦请彭哥看一下。

**Comment by zhusongyu** [comment]
补充下下载的bin文件。不能直接传bin文件，所以我压缩成zip包了。
[048971255a04cbd33624172d00f8aedd_upd_xiaoxun.ro_skates.v1.bin.zip](https://github.com/MiEcosystem/ios-rn-sdk/files/2132414/048971255a04cbd33624172d00f8aedd_upd_xiaoxun.ro_skates.v1.bin.zip)

**Comment by Smart-XiaoLeiGe** [comment]
我也遇见这个问题了，
```
另外，当我下载文件后用MHPluginFS.readFile接口时，读取失败，
MHPluginFS.readFile(result.filename, (success, utf8Content)
```

@ LiuMengzhou 烦请 Copypeng 和 彭哥看一下。

**Comment by Smart-XiaoLeiGe** [comment]
@LiuMengzhou

**Comment by Smart-XiaoLeiGe** [comment]
MHPluginFS.readFileToBase64(result.filename, (success, base64Content) => {
                            if (success) {
                                MHPluginFS.dataLengthOfBase64Data(base64Content, (length) => {
                                    var bytes = MyBase64js.toByteArray(base64SubData);
                                    var hexValue = this._bytes2Hex(bytes);
                                    console.log("bin hexValue :"+hexValue);
                                    this._upgradeCheck(version,hexValue.length/2);
                                });
                            }
                        });

    _bytes2Hex(bytes){
        var hex='';
        for (let i = 0; i < bytes.length; i++) {
            hex += this._byte2Hex(bytes[i]);
        }
        return hex;
    }

    _byte2Hex(b) {
        if(b < 0x10)
            return "0" + b.toString(16);
        else
            return b.toString(16);
    }

**Comment by Smart-XiaoLeiGe** [comment]
```
MHPluginFS.readFileToBase64(result.filename, (success, base64Content) => {
         if (success) {
              MHPluginFS.dataLengthOfBase64Data(base64Content, (length) => {
                     var bytes = MyBase64js.toByteArray(base64SubData);
                     var hexValue = this._bytes2Hex(bytes);
                     console.log("bin hexValue :"+hexValue);
                     this._upgradeCheck(version,hexValue.length/2);
                 });
       }
 });

    _bytes2Hex(bytes){
        var hex='';
        for (let i = 0; i < bytes.length; i++) {
            hex += this._byte2Hex(bytes[i]);
        }
        return hex;
    }

    _byte2Hex(b) {
        if(b < 0x10)
            return "0" + b.toString(16);
        else
            return b.toString(16);
    }

```
