### ISSUE TITLE
自定义 OTA 流程

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [MiEcosystem/ios-rn-sdk#31]
Team，

目前，插件里的OTA 升级功能都是调用，MHPluginSDK.openDeviceUpgradePage();，但是这个方法对应的页面，没有找到。现在有自定义OTA流程的需求，该怎么做？

**Comment by Smart-XiaoLeiGe** [comment]
@Copypeng

**Comment by Copypeng** [comment]
WiFi 与 双模设备直接调用该方法即可。

蓝牙设备如何 OTA 是个高频问题，已经整理在 wiki 中。更直白一点的说法就是，就是蓝牙设备 OTA 需要厂商利用蓝牙读写接口自己开发，所以我们也没有提供统一 UI。如果你是蓝牙设备，不要调用改方法，完全自己开发。

能用上的常用接口请参考文档 [rn方式实现蓝牙设备固件升级步骤](https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/blernfirmwareupdate.md)

另，不用@我，我们会定时 check issue，催促不会加快这个过程。
