### ISSUE TITLE
MHPluginSDK.basePath 的包路径 和我实际上传的包路径不一致，导致我一个包适配多个mode，有的model路径不对，获取不到图片

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/ios-rn-sdk#34]
问题描述

- [ ] 我打包了一个包名为 com.chuangmi.remoteversion2.ios 插件，适配了多个model；

- [ ] 实际上只有在 本地调试这个插件的时候获取图片路径是ok的；

- [ ] 在把RN的js 上传到服务端后，下载路径变了；

- [ ] 例如（com.chuangmi.remoteversion2.ios_143_41/Resoucres），然后图片就没有，加载不到数据

**Comment by Copypeng** [comment]
重复 https://github.com/MiEcosystem/ios-rn-sdk/issues/33
