### ISSUE TITLE
关于API 的困惑，还望帮忙解答一下。

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [MiEcosystem/ios-rn-sdk#35]
关于API 的困惑，还望帮忙解答一下。
1.
# 目前，我们用下图的两个API：get_user_device_data 和 set_user_device_data，git 地址 https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/callSmartHomeAPI.md
set_user_device_data  api 中uid 这个字段对于我们的历史数据来说有可能会有两个，一个是下载历史数据时的user ，一个是真正上传的时候的user，请问用哪个？
 
>> 为什么会存在两个user？
自己只能上报自己的数据，也只能取自己的数据。
倘若用户自己有多个同样设备的情况下，uid依旧只有一个，用did来判断不同的设备。

### A拿了一部分甲醛仪的历史数据，B拿了一部分，插件把历史数据存在本地，此时就是两个user，我是不是哪儿理解错了？

**Comment by Copypeng** [comment]
你说的这两个 API 是存储用户有关数据，跟着用户的 uid （账号）走，即使删除了该设备，同用户通过同 model 的另一设备依然能访问该数据。你可以理解为一个数据库，按 uid + model 作为 key 存了该数据。

还有另外一个 API 在文档中有描述，存储设备相关数据，跟着设备 did 走，即该设备被删除了，数据就没有了。同样可以理解为一个数据库，按 did 作为 key 储存。

请根据自己的业务需求决定使用。外人不能理解、指导你们的业务。
