### ISSUE TITLE
网关数据和上传数据不一致问题

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [MiEcosystem/ios-rn-sdk#37]
甲醛仪会广播数据给小米网关，那广播的数据中，哪部分会上传到小米云？插件也会上传历史数据到小米云，两边现在看起来不一致，需要确认一下，修改成一样的数据。

**Comment by Copypeng** [comment]
不知，这里只能解答跟米家 iOS RN SDK 的问题，具体接入参考 iot 平台，以及向对接 PM 寻求文档。
