### ISSUE TITLE
关于MHPluginSDK中callMethod中回调方法参数response在不同情况下数据结构不一致问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/ios-rn-sdk#38]
MHPluginSDK里面的callMethod的回调方法callback(isSuccess, response)，response里面是有error code这个参数，但是在通过局域网向设备发送命令时，response却没有error code。

我们的插件之前同事开发的旧的代码是有去判断response里面的error code或者error message，现在在局域网下就会有问题。

isSuccess是表示网络请求（链路请求）是否成功还是向设备发送指令发送成功，文档里面没有明确的说明这些字段具体意义，再者isSuccess和response里面的code意义是一致的么？

我现在测试的是method是get_prop，测试了一些其他method也会有该问题，请帮忙看一下，谢谢。

**Comment by Copypeng** [comment]
isSuccess 是代表网络请求是否成功。response 就是设备的回复，其中的 code 应该在设备 profile 中规定。
