### ISSUE TITLE
关于设备删除后的通知问题

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/ios-rn-sdk#39]
1.现在插件里调用删除设备,删除后没有提供一个回调来通知插件删除本地数据
2.如果用户没打开插件,直接在列表里删除设备/直接重置设备,本地保存的用户数据是不是也要处理下

**Comment by Copypeng** [comment]
本地数据具体是指?

**Comment by BaroneX** [comment]
例如本地存储的延时关灯数据这些

**Comment by Copypeng** [comment]
额，我是说，具体使用的哪些接口或者方法存储的数据。
