### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by Braveleon** [MiEcosystem/ios-rn-sdk#40]

**Comment by Braveleon** [comment]
ubuntu系统打包报错
sh: md5: command not found
这个错误不知道是怎么意思能解决下吗

**Comment by Copypeng** [comment]
我们只在 MacOS 下测试过打包脚本，其他系统可能稍微有差异。打包脚本是开源的，可以自行查看编辑，一般是路径命令配置的差异。

**Comment by Braveleon** [comment]
我这边有老的没加密的源码，但是打包后签名不正常，新的都是加密后的，能给下packagePluginAndSign的源码文件吗？谢谢了，我的邮箱brave_leon@163.com

**Comment by Copypeng** [comment]
已更新至 pack 分支
