### ISSUE TITLE
  MHPluginSDK.openPrivacyLicense中的URL是第三方路径还是小米提供

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/ios-rn-sdk#46]
MHPluginSDK.privacyAndProtocolReview("license","https://www.xiaomi.com","privacy","https://www.xiaomi.com");
样例种所需要传入的URL是我们自己维护的使用和隐私协议吗？还是由小米提供的？

**Comment by pencilCool** [comment]
现在支持的是：传入本地html 的url。
网页放到小米的服务器上这个能力还没开放出来。

### 本地html具体的做法是：
将你的html 文件  `your_html_file.html`  放在Resources 目录下，那么
`MHPluginSDK.basePath + your_html_file.html `  就是你的本地url。
传入API就可以了
