### ISSUE TITLE
设置插件时区页面如何调用？

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/ios-rn-sdk#47]

**Comment by Copypeng** [comment]
SDK 似乎并没有提供标题所说页面。或提供更详细的描述。

**Comment by zhaolios** [comment]
![img_0653](https://user-images.githubusercontent.com/13412744/43443482-938ad6fe-94d3-11e8-81c8-08b70a4f5757.PNG)

![img_0654](https://user-images.githubusercontent.com/13412744/43443562-d1ce2f56-94d3-11e8-8a33-e4d909554927.PNG)
--------------------------------------------------------------
貌似你们的更新记录里面提到过，并且有插件使用了这个页面@Copypeng 
--------------------------------------------------------------

**Comment by Copypeng** [comment]
我知道了，这个时区设置页面是新功能开发给摄像头类产品先使用的。对插件还未提供接口。我们尽量8月份版本导出提供。

**Comment by Copypeng** [comment]
不活跃。
