### ISSUE TITLE
关于packagePluginAndSign打包脚本问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/ios-rn-sdk#48]
packagePluginAndSign这个脚本中有对插件源码进行对称加密生成codeSign这样一个文件。不知道这个codeSign是否有必要呢？因为已经对mainbundle.js所在目录进行哈希加密了，这样已经可以达到代码验证的目的了，为什么还需要codeSign呢？

**Comment by Copypeng** [comment]
有必要，请按文档所示使用打包工具。我们签名机制会保证服务器拿到的包是开发者上传的包，同时App 拉取到的包依然是这个包。具体细节不赘述。

**Comment by TheWalkingDead1024** [comment]
了解。只不过我发现你们有两处都进行了签名，我只是感觉只需要一处签名即可。既然细节未知，就按照你们说的打包吧。

**Comment by Copypeng** [comment]
都是有必要的，给不同的地方用。我是说具体细节不暴露了。

**Comment by TheWalkingDead1024** [comment]
了解，谢谢
