### ISSUE TITLE
请问怎样才能在没有实体硬件时试用SDK里的Demo?

### ISSUE THREAD

**Issue by agalloch21** [MiEcosystem/ios-rn-sdk#5]
前提: 我们有企业开发者账号, 已经申请了新硬件进行开发, 但是还没有实体硬件做完. 目前在做rn扩展程序时想试用SDK目录下的Demo

尝试: 参照文档, 做了两种尝试

1. 

- 使用createPlugin创建新扩展程序

- 打包签名并上传

- 设置为白名单测试

- 启动Node服务器

- 在米家App上打开开发者模式, 填入我们申请的model id和新创建的插件包名,  选中创建一个相应的虚拟设备

- 在设备列表里并没有发现虚拟设备图标(设备数量倒是+1了)

2. 

- 前面步骤相似, 但是在米家App上打开开发者模式时, 填入文档里示例中的model id和sdk中demo的包名. 
model id: com.xiaomi.demo.model
插件包名:com.xiaomi.svgdemo.ios
选中创建一个相应的虚拟设备

- 在设备列表里也没有发现虚拟设备图标(设备数量也+1了)

请问, 如何能快速的看到demo在米家app里运行的效果?

**Comment by Copypeng** [comment]
你好，在开发者模式下，按文档步骤开始调试，并不需要你打包上传至 iot 平台。你启动 node server 之后，米家 app 会运行你本地 server 的 代码。即时修改，刷新或者重新进入插件即生效。

虚拟设备功能由于新版本的多家庭功能上线后，目前正在调整，可能会出现错误。

假如你们没有实体设备可供调试，有一下几种方式可供参考：
1，请你们的嵌入式提供开发板；
2，任意选一款已经上市的米家设备，在开发者选项中，model 填该设备，其余选项填自己的插件包名、地址等。当你进入该设备时，会启动本地的插件包。

**Comment by agalloch21** [comment]
您好, 感谢回复.
已经上市的米家设备的model名不好去问, 请问官方有没有可以用来测试的model id. 我试过com.xiaomi.demo.model这个id, 设备个数增加了但是设备列表里并没有显示.

**Comment by Copypeng** [comment]
因为那个 model 只是 demo …… 如果你的米家中有任意一款已经添加到设备列表的设备，可以将设备名发送至 pengyong@xiaomi.com，我查询后将 model 发送给你。

**Comment by Copypeng** [comment]
虚拟设备在新版本已重新上线。
