### ISSUE TITLE
插件打点

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/ios-rn-sdk#51]
插件打点的API->`addRecord(type, value, extra)` 已弃用,是否有替代的方法?
安卓端打点接口是可用的https://github.com/MiEcosystem/NewXmPluginSDK/blob/master/API%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/%E7%BB%9F%E8%AE%A1%E7%9B%B8%E5%85%B3API.md
MHLog 模块提供扩展程序内的日志打点、统计打点（内测中）功能。
我看方法`addLog`只是在用户反馈的时候上传日志,和打点统计不太一样

**Comment by Copypeng** [comment]
你好，我以为这条有人回复过了。RN 这块只提供日志打点，数据会在用户反馈时上报。
