### ISSUE TITLE
插件主页面不能左划返回

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [MiEcosystem/ios-rn-sdk#54]
插件主页面不能左划返回
![img_0195](https://user-images.githubusercontent.com/1797012/44575448-a2196c00-a7be-11e8-8e1a-99dcdd28127f.PNG)
代码设置如下：
![screen shot 2018-08-24 at 4 54 42 pm](https://user-images.githubusercontent.com/1797012/44575478-b1001e80-a7be-11e8-8ef3-98e6e823e498.png)

**Comment by Copypeng** [comment]
主页确实不行，后续我们升级 SDK 时，提供一个统一能力吧。

**Comment by Smart-XiaoLeiGe** [comment]
好的，谢谢。

**Comment by Copypeng** [comment]
会在Q4框架升级时提供。
