### ISSUE TITLE
米家beta4.5.0.3版本看不到创建的虚拟设备？

### ISSUE THREAD

**Issue by wyc123456** [MiEcosystem/ios-rn-sdk#56]
- 
![wechatimg83](https://user-images.githubusercontent.com/19943186/44643421-0e84ad00-aa03-11e8-81b3-c71cfdab7ed5.jpeg)
![wechatimg84](https://user-images.githubusercontent.com/19943186/44643423-117f9d80-aa03-11e8-88e3-3a72154cd506.jpeg)
之前版本好像没问题，重新下载安装米家beta就看不到了？开发者模式里面有勾选“创建一个相应的虚拟设备”；“我的”图片那边也显示有“一个智能设备”；首页的dev里面却没有设备，是我配置错了？

**Comment by Copypeng** [comment]
你好，应该是 beta 的 bug，已经在修复并近期提供新版 beta。

**Comment by iHealthBaoLei** [comment]
@Copypeng 请问新版beta什么时候能发布出来？

**Comment by Copypeng** [comment]
你好，我们昨夜提交了新版本。今天晚些时候就会同步 beta，依然是 iot 平台上提供的地址下载。

**Comment by brainweiyi** [comment]
我的是会有一个toast弹出“网络异常”，但是明明是同一个局域网内，Telnet 也可以通

**Comment by Copypeng** [comment]
抱歉这个自动发布的版本依然有问题，晚些我同事会 fix 这个问题并上传新包。

**Comment by Copypeng** [comment]
新包亲测可用，房间列表拉至最右，会出现一个名为 Dev 的房间，虚拟设备会出现在房间中。

**Comment by zhuxinleibandou** [comment]
4.5.0.3在dev房间列表下没有看到虚拟设备 - - 开发者模式下确认model名和IP以及扩展包名正确，model也设置了白名单，model需要申请上线吗？目前设置了基础配置
