### ISSUE TITLE
获取device token这个接口callback返回值与文档意义表达不一致

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/ios-rn-sdk#57]
MHPluginSDK.md 中有如下接口描述
MHPluginSDK.deviceToken((error,token)=>{
    if(!error){
    	//console.log(token)
	}
});
实际调试中发现，如果能拿到token，该接口callback中error值为true（可能error应该是isSuccess），请确认并更正一下。

**Comment by Copypeng** [comment]
抱歉，示例代码中写错了，已更改。
