### ISSUE TITLE
该 model 必须是一个已上线或在白名单中的model

### ISSUE THREAD

**Issue by sofichael** [MiEcosystem/ios-rn-sdk#61]
创建虚拟设备调试，配置了一个model，后台没找到添加白名单的入口。能说明下在那吗？

**Comment by Copypeng** [comment]
model 对应的硬件通过审核之后，按文档引导，需要完成基础配置。
在“我的硬件”列表中，每个 model 后面都有权限管理，进入之后配置你的开发者账号权限。

**Comment by sofichael** [comment]
按照你的方式配置完成，也没有发现有虚拟设备出现，描述的步骤不够完善啊...

**Comment by zhuxinleibandou** [comment]
楼主解决这个问题了吗？ 我也设置了白名单 创建虚拟设备后 没找到虚拟设备

**Comment by sofichael** [comment]
@zhuxinleibandou 设备通过审核后才会出现，如果已经审核过， 退出账号，杀掉app，重新登录尝试，还不行就删了app再尝试。
