### ISSUE TITLE
创建虚拟设备列表不显示，提示“网络异常”

### ISSUE THREAD

**Issue by brainweiyi** [MiEcosystem/ios-rn-sdk#62]
在同一个局域网内，telnet ip 8081 也可以通，后台model也有

![191536303923_ pic](https://user-images.githubusercontent.com/3353932/45203682-7f538100-b2af-11e8-8af3-c328fa1db262.jpg)

**Comment by Copypeng** [comment]
model 是啥？

**Comment by brainweiyi** [comment]
090615.curtain.sidt82 @Copypeng

**Comment by Copypeng** [comment]
等新包吧，那个包依然有问题，白高兴一场。

**Comment by Copypeng** [comment]
新包亲测可用，房间列表拉至最右，会出现一个名为 Dev 的房间，虚拟设备会出现在房间中。

**Comment by Copypeng** [comment]
https://github.com/MiEcosystem/ios-rn-sdk/issues/56
