### ISSUE TITLE
在“我的”页面未看到“开发者模式”菜单

### ISSUE THREAD

**Issue by happy2discover** [MiEcosystem/ios-rn-sdk#63]
开发者账号已加入企业开发组
![wechatimg121](https://user-images.githubusercontent.com/7375483/45292114-c7300d80-b526-11e8-8e47-b8e8be4fcef1.png)

**Comment by Copypeng** [comment]
你好，文档中没有相关描述？

**Comment by iHealthBaoLei** [comment]
@happy2discover 前一阵子刚弄完，需要按文档配公钥，然后重新登录，就可以了
