### ISSUE TITLE
MHBluetooth.writeHexDataWithCallback使用问题

### ISSUE THREAD

**Issue by iHealthBaoLei** [MiEcosystem/ios-rn-sdk#64]
对于writeHexDataWithCallback(hexString, characteristicUUID, serviceUUID, type, callback) AL-[113,)方法，文档里没有说明传入hexString的长度限制，目前测试发现：

1、长度较短时，有callback，返回isSuccess=true，虽然文档没说，但是其实就是调用API成功，而并不是write成功；
2、长度过长时，没有callback，感觉应该是API健壮性需要改进；
3、长度为奇数时，字符串前面补‘0’，虽然文档没说，但是也可以理解；

问题：
1、能否提供一个接口，返回最大发送长度，这样开发者在发送较长数据时可以有效分包，多次调用writeHexDataWithCallback 方法，高效利用蓝牙。类似iOS 9开始提供的：maximumWriteValueLengthForType方法。
2、如果暂时不能提供接口，那么是否可以给出一个具体的数值？因为最大发送长度和手机、蓝牙模块有关，这里提供了产品正在使用的小米蓝牙模块Model: MHCB03P，芯片：EFR32。

**Comment by Copypeng** [comment]
1，callback 中的 BOOL 参数代表是否调用 write 操作成功。至于数据是否写到设备，参考苹果CoreBluetooth 文档，跟 type 相关，peripheral:(CBPeripheral *)peripheral didWriteValueForCharacteristic:(CBCharacteristic *)characteristic error:(nullable NSError *)error回调我们有导出对应的通知。

2，假如传入的 callback 不为空，这个方法设计成的是一定会执行 callback。是数据太长超过系统最大值导致系统蓝牙 write 操作卡住了? 这个需要关注一下。

3，HexString 与 NSData（bin）互转不能有奇数个 HexString ，这个改成返回错误而不是帮开发者自动补全更好。我们框架升级时修改。

4，ATT_MTU 是个历史问题，Apple 之前不提供相关 API，这个框架设计时才 iOS 7。第4季度我们升级框架时加入读取 MTU 的方法。现在按最大 20 bytes 处理。

**Comment by iHealthBaoLei** [comment]
@Copypeng 谢谢！
