### ISSUE TITLE
米家app崩溃问题

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/ios-rn-sdk#65]
在开发过程中我们想利用MHXiaomiBLE.encryptMessageXiaoMiBLE(）进行加密时，报错{"message":"login first","code":1}，貌似说我要登陆。

我修改了逻辑，在加密前，想先用MHXiaomiBLE.loginXiaoMiBLE（）进行登录，结果这方法直接导致米家app崩溃。

请注意，这里是米家app崩溃，而不是扩展程序崩溃。

我后来移植了米家自带的Demo（com.xiaomi.croebledemo.io）中的XiaoMiBLEMainPage.js逻辑，结果发现登录方法依然会导致米家app直接崩溃。

请问我应该如何加解密？

**Comment by Copypeng** [comment]
小米蓝牙协议的设备，绑定后，每次连接也需要使用小米蓝牙协议中的登录协议，这是一种鉴权机制，否则即使直接建立 BLE 连接，设备过几秒应该也会自动断开。

总之，所有需要连接设备后进行的操作，都需要登录，即 MHXiaomiBLE 模块中的loginXiaoMiBLE方法。

如果使用 demo login 设备 crash 了，应该是开发中的设备没有正确实现安全芯片（锁）类产品的协议。而米家 App 没有做好这种错误的处理。

根本的解决方案需要你们检查修正设备固件。

最后，希望能提交 crash log，我们尽量避免 crash，把错误返回给插件。

**Comment by Copypeng** [comment]
不同模块封装的相同方法，只是锁的加解密不在这个模块。可以尝试同时使用，我们没有验证过。

**Comment by gaopingfly** [comment]
> 小米蓝牙协议的设备，绑定后，每次连接也需要使用小米蓝牙协议中的登录协议，这是一种鉴权机制，否则即使直接建立 BLE 连接，设备过几秒应该也会自动断开。
> 
> 总之，所有需要连接设备后进行的操作，都需要登录，即 MHXiaomiBLE 模块中的loginXiaoMiBLE方法。
> 
> 如果使用 demo login 设备 crash 了，应该是开发中的设备没有正确实现安全芯片（锁）类产品的协议。而米家 App 没有做好这种错误的处理。
> 
> 根本的解决方案需要你们检查修正设备固件。
> 
> 最后，希望能提交 crash log，我们尽量避免 crash，把错误返回给插件。

附件是崩溃日志。

请问，能从日志中看到硬件设备没有实现哪个协议吗？因为我们的android是可以正常加解密的。按理来说 ios 不应该出现这个问题。 请帮忙分析一下，谢谢。

[日志.txt](https://github.com/MiEcosystem/ios-rn-sdk/files/2379199/default.txt)

**Comment by gaopingfly** [comment]
@Copypeng @iHealthBaoLei @chundong @kyou @kangkai 

项目比较急。求大神把上面的问题看一下。感谢

**Comment by iHealthBaoLei** [comment]
@gaopingfly 分享一下对于MHXiaomiBLE的理解（我在开发BLE设备，对于MHXiaomiBLE和MHBluetooth也是探索了一番，现在我主要用的是MHBluetooth中的方法，大部分功能已经实现）

1、添加设备成功后，会进入插件中，此时设备处于连接状态，先调用getDefaultDevice拿到did和mac，然后调用loginXiaoMiBLE，可以登陆成功，设备端串口会依次打印连接成功、绑定成功、登陆成功；

2、退出插件，断开设备连接，再次进入插件，
a、调用scanXiaoMiBLE方法，监听通知didFoundXiaoMiBLEDevice，收到通知后，调用loginXiaoMiBLE方法，同样可以登陆成功(但是需要注意，不要使用didFoundXiaoMiBLEDevice中的did，那个是mac地址的字节翻转字符串，不知道小米为何设计成不一致的，还请小米同学看一下@Copypeng ) 
b、直接调用loginXiaoMiBLE方法，也可以扫连成功（就像我之前提过的，MHBluetooth. scanAndConnectForSeconds=loginXiaoMiBLE）

3、我的设备没有实现小米安全芯片加密的功能，所以调用encryptMessageXiaoMiBLE，报错和你的一样：{"message":"login first","code":1}，彩色在登陆过程中，App会从设备端得到加密用的参数，可能就像小米同学说的那种，你的设备实现的不对导致的报错，而并不是没有登陆。

4、MHXiaomiBLE.scanXiaoMiBLE这个API，
a、设备已经连接，调用这个API后，error为空，device不为空，是个问题 @Copypeng 
b、上一次调用还没返回，再次调用，报错：{"message":"Module is scanning","code":1}，表现正常
c、蓝牙关闭时，调用后，任何返回都没有，是个问题 @Copypeng ，对比调用MHBluetooth. scanAndConnectForSeconds和MHXiaomiBLE.loginXiaoMiBLE，都有错误404返回

5、偶现问题：
a、MHXiaomiBLE.loginXiaoMiBLE后，会调转到添加设备页，点击设备能连接，但无法继续，没有弹框按钮，返回按钮点击无效
b、MHXiaomiBLE.loginXiaoMiBLE后，会跳转到智能页面
c、调用MHBluetooth. scanAndConnectForSeconds后，返回按钮MHPluginSDK.closeCurrentPage()不起作用

感觉MHXiaomiBLE这个模块，问题太多了，希望小米能够完善一下文档，整合一下，最好能够细致地测试一下。

**Comment by gaopingfly** [comment]
> @gaopingfly 分享一下对于MHXiaomiBLE的理解（我在开发BLE设备，对于MHXiaomiBLE和MHBluetooth也是探索了一番，现在我主要用的是MHBluetooth中的方法，大部分功能已经实现）
> 
> 1、添加设备成功后，会进入插件中，此时设备处于连接状态，先调用getDefaultDevice拿到did和mac，然后调用loginXiaoMiBLE，可以登陆成功，设备端串口会依次打印连接成功、绑定成功、登陆成功；
> 
> 2、退出插件，断开设备连接，再次进入插件，
> a、调用scanXiaoMiBLE方法，监听通知didFoundXiaoMiBLEDevice，收到通知后，调用loginXiaoMiBLE方法，同样可以登陆成功(但是需要注意，不要使用didFoundXiaoMiBLEDevice中的did，那个是mac地址的字节翻转字符串，不知道小米为何设计成不一致的，还请小米同学看一下@Copypeng )
> b、直接调用loginXiaoMiBLE方法，也可以扫连成功（就像我之前提过的，MHBluetooth. scanAndConnectForSeconds=loginXiaoMiBLE）
> 
> 3、我的设备没有实现小米安全芯片加密的功能，所以调用encryptMessageXiaoMiBLE，报错和你的一样：{"message":"login first","code":1}，猜测在登陆过程中，App会从设备端得到加密用的参数，可能就像小米同学说的那种，你的设备实现的不对导致的报错，而并不是没有登陆。
> 
> 4、MHXiaomiBLE.scanXiaoMiBLE这个API，
> a、设备已经连接，调用这个API后，error为空，device不为空，是个问题 @Copypeng
> b、上一次调用还没返回，再次调用，报错：{"message":"Module is scanning","code":1}，表现正常
> c、蓝牙关闭时，调用后，任何返回都没有，是个问题 @Copypeng ，对比调用MHBluetooth. scanAndConnectForSeconds和MHXiaomiBLE.loginXiaoMiBLE，都有错误404返回
> 
> 5、偶现问题：
> a、MHXiaomiBLE.loginXiaoMiBLE后，会调转到添加设备页，点击设备能连接，但无法继续，没有弹框按钮，返回按钮点击无效
> b、MHXiaomiBLE.loginXiaoMiBLE后，会跳转到智能页面
> c、调用MHBluetooth. scanAndConnectForSeconds后，返回按钮MHPluginSDK.closeCurrentPage()不起作用
> 
> 感觉MHXiaomiBLE这个模块，问题太多了，希望小米能够完善一下文档，整合一下，最好能够细致地测试一下。

首先，感谢 iHealthBaoLei 的分享。半夜12点写了这么长一篇文档，看出了你的毅力和能力。

其次，我目前遇到的问题很明确，也就是在你分享的第一步时，直接在loginXiaoMiBLE方法调用时米家app崩溃。

其实我也感觉是不是我们蓝牙设备没有实现什么协议，但是该蓝牙设备在用android版本的米家SDK中是没有任何问题的。所以想请米家朋友看看是什么问题。

MHXiaomiBLE.getDefaultDevice(
            (error, device) => {

                if (!error) {
                    console.log('连接设备中');
                    console.log('device.did '+device.did);
                    console.log('device.mac '+device.mac);
                    MHXiaomiBLE.loginXiaoMiBLE(device.did, device.mac, 10, (error, result) => {
                        if (!error) {
                            console.log('设备登陆成功，开始初始化数据');
                        }
                        else {
                            console.log('连接设备失败，XiaomiBLE无法登录');
                        }
                    });
                } else {
                    console.log('连接设备失败，XiaomiBLE无法获取设备');
                }
            }
        );

**Comment by gaopingfly** [comment]
问题有点眉目了。由于android的小米蓝牙通信是我搭建的，android没有问题。我在搭建iOS的环境时出现问题，自然而然以为是sdk的问题。结果貌似是我们蓝牙设备的问题。劳烦各位了。

**Comment by chundong** [comment]
我们发现你们固件把蓝牙芯片的service代码给注释了，你们开启之后在试试看

**Comment by gaopingfly** [comment]
> 我们发现你们固件把蓝牙芯片的service代码给注释了，你们开启之后在试试看。我们上传了一个新的包，你们也可以试试新上传的包有没有问题 @gaopingfly

非常感谢！
更具你的回复，app崩溃的的问题已经解决了。

**Comment by gaopingfly** [comment]
> 回头我对这个 issue 好奇起来，设备上对应的gatt service 都没有，声称安卓登录没问题的论断是怎么来的？

这个我也很郁闷。他们确实把1000的服务注释掉了，然后自己写了个相似的2000服务。一切都能正常。哎
