### ISSUE TITLE
怎样连接米家调试程序

### ISSUE THREAD

**Issue by LuckyDing** [MiEcosystem/ios-rn-sdk#7]
您好，我这边按照文档，创建扩展程序，想连接手机创建相应的虚拟设备，在手机端配置好但是设备列表并不显示。请问如何才能看到界面程序

**Comment by Copypeng** [comment]
虚拟设备暂不可用，请厂商使用自己的硬件直接调试。

虚拟设备调整后会在下个米家版本可用。
