### ISSUE TITLE
MHBluetoothLE.writeWithoutResponse接口怎么没有callback？

### ISSUE THREAD

**Issue by zhusongyu** [MiEcosystem/ios-rn-sdk#70]
参考以下接口时，发现 (error)回调一直没有执行，是怎么回事？
writeWithoutResponse(identifier, serviceUUID, characteristicUUID, msg, callback)

描述：向某设备的某服务的某特征写入数据

参数：

identifier 需要查询的蓝牙设备identifier
serviceUUID 需要查询的service的UUID
characteristic 需要查询的characteristic的UUID
msg 发生到设备端的16进制字符串 例如：'FF00FF00'
callback(error) error表示是否有错误
例子：

MHBluetoothLE.writeWithoutResponse(service.peripheral, service.uuid, CharacteristicUUID_READ_NORDIC, 'FF00FF00', (error) => {
    if (error) {
      MHPluginSDK.showFilTips('数据写入失败');
      return;
    }
  });

但是，如果我使用MHBluetoothLE.writeValue接口，可以正常有 (error)回调的，蓝牙功能基本正常。
之所以想使用writeWithoutResponse接口，是因为蓝牙固件升级时传输太慢，希望看看这个接口能否快一些。

**Comment by gaopingfly** [comment]
我用MHBluetoothLE.writeValue，报“Writing is not permitted”异常，不知道如何解决

**Comment by Copypeng** [comment]
@zhusongyu  这个方法，假如写操作执行成功，没有 error，那 error callback 则不会执行。这个地方设计不好，应该 callback 一次，告诉开发者操作执行成功。

**Comment by Copypeng** [comment]
@gaopingfly 这是系统返回的。开发要有基本的分析定位，不要是问题都到这里来。

**Comment by gaopingfly** [comment]
> @gaopingfly 这是系统返回的。开发要有基本的分析定位，不要是问题都到这里来

不好意思打搅了，我是做app的，确认自己调用方法没有问题，却得到没有权限异常。做蓝牙设备的人又担保自己没有问题。工期赶的急，就只能在这里提问了。目前已经确认是蓝牙设备的问题。万分抱歉。

**Comment by Copypeng** [comment]
> > @gaopingfly 这是系统返回的。开发要有基本的分析定位，不要是问题都到这里来
> 
> 不好意思打搅了，我是做app的，确认自己调用方法没有问题，却得到没有权限异常。做蓝牙设备的人又担保自己没有问题。工期赶的急，就只能在这里提问了。目前已经确认是蓝牙设备的问题。万分抱歉。

不容易，明白。

**Comment by zhusongyu** [comment]
> @zhusongyu 这个方法，假如写操作执行成功，没有 error，那 error callback 则不会执行。这个地方设计不好，应该 callback 一次，告诉开发者操作执行成功。

我们固件升级传输数据较大，需要批量传输Data，请问下推荐使用哪个接口传输好一些呢？

**Comment by Copypeng** [comment]
这个模块都是系统方法的桥接，各自根据业务选择，没有“推荐”这个说法吧。
