### ISSUE TITLE
利用MHBluetoothLE.writeValue（）方法发送失败，说没有权限。

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/ios-rn-sdk#72]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/28840287/45621886-a5013700-bab4-11e8-92a9-e74357f923b2.png">

**Comment by gaopingfly** [comment]
我和设备的同事对过，之前的enableNotify方法设备能收到，writeValue方法无法写入

**Comment by Copypeng** [comment]
系统返回的错误，靠自己了。
