### ISSUE TITLE
MHBluetooth.scanAndConnectForSeconds

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/ios-rn-sdk#73]
MHBluetooth.scanAndConnectForSeconds 方法高概率返回错误码2，请问这错误码代表什么意思？

**Comment by Copypeng** [comment]
错误发生在设备上。参考 MHXiaomiBLE 中的 loginXiaoMiBLE 方法中的说明。

**Comment by JxXiaoXie** [comment]
数据读写失败？可是同一台蓝牙设备，在安卓机上不会出现这样的错误。

**Comment by Copypeng** [comment]
这两系统平台蓝牙差异还蛮大的，是不是设备没有实现对应的services、characteristics

**Comment by JxXiaoXie** [comment]
有实现，执行MHBluetooth.scanAndConnectForSeconds方法后，MHBluetooth.peripheral_didDiscoverServices、MHBluetooth.peripheral_didDiscoverCharacteristicsForService_error等通知都有正常的回调，MHBluetooth.characteristicUUIDsOfServiceUUIDWithCallback方法也有正常回调，再然后就是错误2返回给我了。


原始邮件
发件人:Copypeng-小米notifications@github.com
收件人:MiEcosystem/ios-rn-sdkios-rn-sdk@noreply.github.com
抄送:小谢1170068445@qq.com; Authorauthor@noreply.github.com
发送时间:2018年9月19日(周三) 10:58
主题:Re: [MiEcosystem/ios-rn-sdk] MHBluetooth.scanAndConnectForSeconds(#73)


这两系统平台蓝牙差异还蛮大的，是不是设备没有实现对应的services、characteristics

**Comment by JxXiaoXie** [comment]
应该是最近的米家版本才出现这个问题，以前一直都不会的。

**Comment by JxXiaoXie** [comment]
要不我共享的牙刷设备给你，你再试试？

**Comment by Copypeng** [comment]
千里之外连蓝牙设备？

**Comment by JxXiaoXie** [comment]
DeviceEventEmitter.addListener(MHBluetooth.peripheral_didDiscoverCharacteristicsForService_error, (notification) => {
			alert(JSON.stringify(notification));
    });

你好，这个通知有的时候打印{"service":"FE95", "error": 0}，有的时候打印{"service":"640001-ABCD-ABCD", "error": 0}，为什么呢？注：640001-ABCD-ABCD 是ServiceUUID。

EF95似乎是 kCBAdvDataServiceData 取出来的，那640001-ABCD-ABCD这个呢？

**Comment by Copypeng** [comment]
这个 service 不是米家的，是设备厂商自己的服务。米家的是 FE95,  应该是米家 App 连接设备时，discover 设备上的 service 时一并发现，系统就上报这个通知了。跟 kCBAdvDataServiceData 没有关系。scanAndConnectForSeconds 连接设备没问题了？开始讨论蓝牙知识了嘛。

**Comment by JxXiaoXie** [comment]
讨论下蓝牙知识有利于解决这个bug。

**Comment by Copypeng** [comment]
> 千里之外连蓝牙设备？
> 
> 你有其他米家蓝牙设备吗，我测试都是正常的，你要不要跟固件联调一下，打打 log 定位一下。

我觉得跟固件联调一下，打打 log，看看数据流，应该就知道了。

**Comment by JxXiaoXie** [comment]
好的
