### ISSUE TITLE
getDevicePropertyFromMemCache 取不到版本号

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/ios-rn-sdk#75]
我们是蓝牙设备，在固件更新的地方要取设备的版本号。调用 getDevicePropertyFromMemCache(['version']) 这个方法，有时候能取到，有时候返回为空。
断开设备再连接，也还是取不到。

**Comment by Copypeng** [comment]
每次连接设备时，米家 App 会读取设备上的固件版本号，但它并不是一个 block 的操作。为保证用户体验，即使读取版本号失败依然会正常走完连接过程。

扩展程序可在该值为空时，自己向设备查询版本号。（按 miot 蓝牙协议，应该读取设备 Service fe95，Characteristic 0004 即是版本号）

另外连接时读取版本号的失败率并不高，最近收到两家反馈这个问题了，是上个版本米家 app 有 bug，我们已经 fix。

**Comment by dubiao** [comment]
@Copypeng 新版本的米家，在读取时可以读取正常了。但是给设备升级固件后，读取，还是显示旧的版本号。应该是旧的缓存，请问怎么刷新版本号？
