### ISSUE TITLE
插件调试开关打开不能正常调试啊

### ISSUE THREAD

**Issue by asdfeng** [MiEcosystem/ios-rn-sdk#78]
![1521537260951_ pic](https://user-images.githubusercontent.com/17334138/45736431-836f8f00-bc1d-11e8-9537-0c6bcde22952.jpg)

![1481537260683_ pic](https://user-images.githubusercontent.com/17334138/45736417-7652a000-bc1d-11e8-826e-004a276f5ea3.jpg)

**Comment by LiuMengzhou** [comment]
一步一步来，先关闭其他的开关：1. 离线进入2.商城调试地址

**Comment by asdfeng** [comment]
> 一步一步来，先关闭其他所有的开关：
> 
> 1. 离线进入
> 2. 插件调试
> 3. 商城调试地址
> 4. 商城调试服务器
>    只打开`开发者模式`，看是是否可以正常进入开发者模式
>    然后再打开`插件调试开关`，看能否用Chrome调试

还是不行。`开发者模式`是可以正常进入的，但是打开`插件调试开关`却不能调用Chrome调试。

**Comment by LiuMengzhou** [comment]
那推断是chrome的问题，进入插件的时候，你的chrome主动打开了一个tab页吗？

可以试试这样：
1. 手动打开一个无痕tab页（这样可以无视chrome的缓存）
2. 手动输入网址：http://localhost:8081/debugger-ui
3. 打开插件

**Comment by asdfeng** [comment]
chrome有主动打开一个tab页

**Comment by LiuMengzhou** [comment]
chrome 主动打开的tab页显示正常吗？
是这样？
![image](https://user-images.githubusercontent.com/13726966/46000188-7863a580-c0da-11e8-8ba4-c287b8a1f180.png)
还是显示两行小字。

```
1. 手动打开一个无痕tab页（这样可以无视chrome的缓存）
2. 手动输入网址：http://localhost:8081/debugger-ui
3. 打开插件
```
这个方法试过了么

**Comment by gaopingfly** [comment]
有些无线网络是双频段的，即使链接在同一个网络下，米家的app也会报找不到服务器的异常。你可以找你们的网络工程师看看。或者找一台设备线链，然后打开共享wifi。我们被类似的问题坑了很久，专门去了一趟北京请教小米的人也没正确答复。结果用酒店的网却是正常的。最终想到是网络环境的问题。哎！
