### ISSUE TITLE
白名单测试时图片资源加载异常

### ISSUE THREAD

**Issue by heyupeng** [MiEcosystem/ios-rn-sdk#8]
调试模式下图片显示正常，打包白名单测试后，在大陆地区下插件加载不出图片，将app设置为台湾香港等地区能够加载图片。（移动4g，Wi-Fi下均存在此问题）

**Comment by Copypeng** [comment]
麻烦 model 提供一下。

**Comment by heyupeng** [comment]
经过排查发现打包下来的压缩包里的同名压缩包里的一级文件夹(resources)丢失了，原resources 下的内容全跳到上一级了。

**Comment by Copypeng** [comment]
那就应该是新包打包有问题。切换到非大陆服务器没问题是因为非大陆服务器的包还在旧版本。

**Comment by Smart-XiaoLeiGe** [comment]
同样有这个问题，debug没问题，白名单测试就显示不出来了。
代码如下：
<Image style={styles.bkgImg} source={this.props.app.sourceOfImage("new_version.png")}></Image>
model如下:
yuemee.airmonitor.mhfd1

但是打包后有Resources目录。
