### ISSUE TITLE
几率性出现进入插件后部分图片显示不出来

### ISSUE THREAD

**Issue by assem-shuang** [MiEcosystem/ios-rn-sdk#80]
![image](https://user-images.githubusercontent.com/43430507/45795856-6e076d00-bcd0-11e8-8ba7-10ace35ddfff.png)
如图关机按钮图片正常显示，大件洗前面的图片没有加载出来。

**Comment by LiuMengzhou** [comment]
你好，关机图片和大件洗的图片加载的代码有什么区别？一模一样吗？

**Comment by LiuMengzhou** [comment]
大件洗前面的图片是一直显示不出来吗？还是偶尔显示不出来？
关机图片是一直可以显示？

**Comment by assem-shuang** [comment]
关机按钮图片实现
![image](https://user-images.githubusercontent.com/43430507/45799318-9d71a600-bcdf-11e8-9a6b-215f99fd997d.png)
大件洗图片实现
![image](https://user-images.githubusercontent.com/43430507/45799379-df025100-bcdf-11e8-9e8b-4446df56dbac.png)
实现方法是一样的，是有时会出现，有事在运行过程中出现，大多数都是在米家点击插件进入插件时出现

**Comment by LiuMengzhou** [comment]
两者的区别在于后者用的是`data.imageNormal`，确定该变量每次都不为空；

如果`data.imageNormal`肯定没问题，那可能是`isStatic`的字段问题。你去掉试试看呢。

**Comment by assem-shuang** [comment]
这个都试过，isStatic也是后来尝试加上来的，关闭按钮的图片也会出现没有的情况

**Comment by LiuMengzhou** [comment]
@assem-shuang 
不知道问题解决没，我的建议还是打印一下图片路径呢，如果如果路径不为空，去打印的路径下check一下图片是否确实存在。

**Comment by assem-shuang** [comment]
没有解决，找不到正确的思路，图片加载不出来是几率性的，有时候插件运行时有的图片会刷新出来。

**Comment by assem-shuang** [comment]
> @assem-shuang
> 不知道问题解决没，我的建议还是打印一下图片路径呢，如果路径不为空，去打印的路径下check一下图片是否确实存在。

没有解决，找不到正确的思路，图片加载不出来是几率性的，有时候插件运行时有的图片会刷新出来。

**Comment by assem-shuang** [comment]
> @assem-shuang
> 不知道问题解决没，我的建议还是打印一下图片路径呢，如果路径不为空，去打印的路径下check一下图片是否确实存在。

**Comment by assem-shuang** [comment]
@LiuMengzhou 
没有解决，找不到正确的思路，图片加载不出来是几率性的，有时候插件运行时有的图片会刷新出来。

**Comment by LiuMengzhou** [comment]
@assem-shuang 
不用说‘您’，太客气了。

首先，图片的加载不出来应该和这个没什么关系。还需要你再排查排查。

然后你反映的可能拉取到旧插件代码的问题，我们这里未能复现，在这里问你两个问题：
1.  你是如何判断插件的版本是最新的还是旧的？我们一般通过显示版本号。
2. 如果确定是清除缓存之后能够拉取到旧版本的插件代码，那么方便提供更详细的复现条件和步骤吗？（比如米家APP的版本：线上版或者测试版，版本号等）我们后续交与测试复现并解决。

**Comment by assem-shuang** [comment]
@LiuMengzhou 
1. 判断插件新旧我是根据我的UI判断，我的最新版本把部分UI显示效果屏蔽了，在反复清理缓存时经常出现没有屏蔽的UI，卸载米家APP后重新安装再没有出现过这个问题
2. 使用的是APP store里面的版本，之前用的应该是4.8.5，卸载后使用的是4.8.6

**Comment by Smart-XiaoLeiGe** [comment]
这个问题，我可以提供一个方案，我们的插件之前也有图片出不来的情况，不过我们是页面1的图没问题，页面2的图出不来，然后我在页面1加一个页面2图片的Image，然后页面2的图就出来了。。。FYI
