### ISSUE TITLE
MHPluginSDK.getDevicePropertyFromMemCache

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/ios-rn-sdk#84]
MHPluginSDK.getDevicePropertyFromMemCache(["isNew"], (props) => {
    console.log(props);
});

请问下isNew这个属性的含义？

**Comment by pencilCool** [comment]
含义是：
是否为新连接的设备

**Comment by JxXiaoXie** [comment]
嗯，新添加一台设备，这个值是true. 如果我再把这设备删了，再重新添加，isNew的值还是为true吗？

**Comment by Copypeng** [comment]
你们应该用不上吧，扩展程序进入之后，这个字段应该就为 false 了，因为用户都已经进入到扩展程序内了，开始使用这个设备。

**Comment by JxXiaoXie** [comment]
要用到，如果用户是新添加进来的设备，需要删除设备内存有的数据。这里我需要知道用户是从设备列表进来的，还是新增加进来的。

**Comment by Copypeng** [comment]
原来想这么用，可是这个字段你试一试，是不是插件里获取到的永远是 false。

**Comment by JxXiaoXie** [comment]
还真是，一直是false

**Comment by JxXiaoXie** [comment]
删了设备，再添加进来是false
删了设备，删了app，重装后再添加设备还是false
