### ISSUE TITLE
分享钥匙成功，但更新和删除钥匙失败

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/ios-rn-sdk#87]
我在10秒内，分别用米家的分享钥匙、更新钥匙、删除钥匙的方法。得到分享成功，更新失败和删除失败的数据。请问我那里做错了？

得到的数据：

 1、 shareSecureKey ok {"message":"ok","result":"ok","code":0}

2、 updateSecureKey error {"error":{"localDescription":"未能完成操作。（“MiHomeNetworkErrorRemote”错误 -1。）","code":-1}}

3、deleteSecureKey error {"error":{"localDescription":"未能完成操作。（“MiHomeNetworkErrorRemote”错误 -8。）","code":-8}}

采用的方法：

 1、 myShareSecureKey() {
        var now = Math.floor(Date.now() / 1000);
        MHPluginSDK.shareSecureKey(MHPluginSDK.deviceId, this.state.text, 1, now, now + 10, [], false, (isSuccess, response) => {
            if (!isSuccess) {
                console.log("shareSecureKey error " + JSON.stringify(response));
            }else{
                console.log("shareSecureKey ok " + JSON.stringify(response));
            }
        });
    }

2、myUpdateSecureKey(){
        var now = Math.floor(Date.now() / 1000);

        MHPluginSDK.updateSecureKey(MHPluginSDK.deviceId, this.state.text , 1, now, now + 20, [],(isSuccess,response)=>{
            if(!isSuccess){
                console.log("updateSecureKey error " + JSON.stringify(response));
            } else {
                console.log('updateSecureKey ok ' + JSON.stringify(response))
            }
        });
    }

3、 myDeleteSecureKey(){
        MHPluginSDK.deleteSecureKey(MHPluginSDK.deviceId,this.state.text ,(isSuccess,response)=>{
            if(!isSuccess){
                console.log("deleteSecureKey error " + JSON.stringify(response));
            }else{
                console.log('deleteSecureKey ok ' + JSON.stringify(response))
            }
            //success
        })
    }

**Comment by gaopingfly** [comment]
> 抱歉不知道，看不了，参数都是外部变量，你让别人怎么给你看？
> 
> 我只能说这个服务很稳定，没问题，线上一直在用。参考文档对参数说明自己debug吧。
> 
> 最后希望你自己发现哪错了之后更新并关闭这个issue。

你好，
MHPluginSDK.deviceId是获取当前的设备，这个是米家的api。
唯一的this.state.text 是自己填的，这个分享钥匙，更新钥匙，和删除钥匙都是一致的，用的是用户的手机作为uid。分享钥匙成功但其他两个功能失败。
now值的定义都上面有写
其他都是米家反馈的回调参数。
所有的参数都是按照米家app填写的。我不认为这有什么看不懂的，只是你没有认真看而已。
其次，作为一个平台的东西，没有任何解决方案，只告诉用户说平台是正确的，你们自己看着办？

**Comment by gaopingfly** [comment]
最起码你要告诉我你们报的错是什么意思吧。只有编号 -1 -8。 文档上又没有，我怎么知道是什么意思？

**Comment by Copypeng** [comment]
所以问题的根源找到了？

**Comment by gaopingfly** [comment]
> 所以问题的根源找到了？

恩，问题找到了。是我的问题。

分享用的是userId, 删除和更新用的是keyId。没仔细看，以为都是userId
