### ISSUE TITLE
关于IOS插件本地持久化问题

### ISSUE THREAD

**Issue by wyc123456** [MiEcosystem/ios-rn-sdk#88]
麻烦帮忙看看，我在插件中使用AsyncStorage保存了一些程序的配置信息。但是如果我要清除掉这些配置信息，我就要卸载米家App重新安装才可以，我在设置里面清除缓存或者删除设备重新配网都是没有办法清除掉AsyncStorage保存的信息。是否有其他方法可以替代AsyncStorage实现本地持久化并且在插件代码重新加载能够清除这些配置信息

**Comment by LiuMengzhou** [comment]
@wyc123456 
你好，很高兴你提出issue。

用`AsyncStorage`进行本地持久化，APP无法控制。

可以使用`MHPluginSDK.saveInfo`和`MHPluginSDK.loadInfoCallback`进行轻量数据的存取。详见[MHPluginSDK文档](https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/MHPluginSDK.md#saveinfoinfo)。

还可以使用MHPluginFS模块进行大文件的存取，详见[MHPluginFS文档](https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/MHPluginFS.md#mihomeplugin-api%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3)。

**Comment by wyc123456** [comment]
@LiuMengzhou 好的，谢谢
