### ISSUE TITLE
调用 MHBluetoothLE.writeValue() 方法，只有chara 有数据，msgData 和error 都无数据，发送成功了吗

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/ios-rn-sdk#89]
调用方法，请问是成功了吗，那为什么蓝牙设备没有收到数据

调用 MHBluetoothLE.writeValue() 方法；

	参数1: 58A1AA04-9BE7-6484-B9F0-CCA7DDD2D2EB
	参数2: 4A6E4000-5E16-459A-9E5B-86F23A314181
	参数3: AA010103010003000104D3

	 MHBluetoothLE.writeValue(this.state.device.peripheral.identifier,UUID_SERVICE, UUID_LED_READ_WRITE,'AA010103010003000104D3', (error, chara, msgData) => {
	      if (error) {
	          console.log('writeValue-----error--'+JSON.stringify(error));
	      }
	      console.log('writeValue-----chara--'+JSON.stringify(chara));
	      console.log('writeValue-----msgData--'+JSON.stringify(msgData));
	});
	
	

返回结果

>* error 结果为undefined
* msgData 结果为undefined
* chara 结果

	{
	    "service": "4A6E4000-5E16-459A-9E5B-86F23A314181",
	    "isBroadcasted": false,
	    "uuid": "4A6E4001-5E16-459A-9E5B-86F23A314181",
	    "descriptors": {},
	    "properties": "unknown",
	    "isNotifying": false,
	    "peripheral": "58A1AA04-9BE7-6484-B9F0-CCA7DDD2D2EB"
	}

**Comment by Copypeng** [comment]
我理解可以跟issue 90合并？
https://github.com/MiEcosystem/ios-rn-sdk/issues/90
