### ISSUE TITLE
急急急

### ISSUE THREAD

**Issue by CGseng** [MiEcosystem/ios-rn-sdk#9]
peripheral_didUpdateValueForCharacteristic_error监听收到蓝牙设备的通知，返回notification中带的value是什么类型数据，文档上面没有说明

**Comment by Copypeng** [comment]
一般是一个数组包含 error 和其他有效信息。数据都拿到了，类型自己打印一下即可。

**Comment by CGseng** [comment]
我拿到的是一串字符，没有类型

**Comment by CGseng** [comment]
你好，我这边拿到"value":"/gEAEk4iAAAIARAFIAEoAIDn",这种数据，请教一下用什么方式解码

**Comment by Copypeng** [comment]
你好，SDK 对设备消息是透传的。你收到的数据即是设备端发送的数据。
