### ISSUE TITLE
我向蓝牙写入数据，msg 是undefine ，那我如何知道我的读写操作是否成功了呢

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/ios-rn-sdk#90]
1.开启 event.peripheral_didUpdateValueForCharacteristic_error 某服务特征内容发生改变(读取或者通知) 

	componentDidMount(){
	
	 this.__didWriteValueForCharacteristic_error_Listener = DeviceEventEmitter.addListener(MHBluetoothLE.event.peripheral_didWriteValueForCharacteristic_error, (perpheral) => this._didWriteValueForCharacteristic_error(perpheral));
	 
	}
	
	_didWriteValueForCharacteristic_error(body){
	    var error = body[0];
	    var characteristic = body[1];
	    var msgData = body[2];
	    console.log('-----------向某服务特征写入数据完成--error-----------'+ JSON.stringify(error));
	    console.log('-----------向某服务特征写入数据完成--characteristic-----------'+ JSON.stringify(characteristic)); 
	    console.log('-----------向某服务特征写入数据完成--msgData-----------'+ JSON.stringify(msgData)); 
	    
    }
    
    
    
    
    
    
	_writeValue(characteristic,msg,isOn){
	    msg='AA010103010003000104D3';

	    MHBluetoothLE.writeValue(characteristic.peripheral, characteristic.service, characteristic.uuid, msg, (error, characteristic) => {
	      
	      console.log("writeValue---error " + JSON.stringify(error));
	      console.log("writeValue---characteristic " + JSON.stringify(characteristic));

	      if (error) {
	        console.log("writeValue---error " + JSON.stringify(error));
	        this._lightSwitch.setSwichByProps(!isOn);
	        MHPluginSDK.showFailTips(error.message);
	        return;
	      }
	      else {
	
	        console.log("writeValue---success " + JSON.stringify(error));
	        if (isOn) {
	          this.setState({"fledColor": '#FF0000'}); //先变红色
	        }
	        else {
	          this.setState({"fledColor": '#330000'}); //先变红色
	        }
	      }
    });

	 }   
	 
	 
2.向蓝牙模块写入数据 _writeValue(characteristic,msg,isOn)；
	  
 处理_didWriteValueForCharacteristic_error 的方法
 log如下
 
 
	 -----------向某服务特征写入数据完成--error-----------null
	 -----------向某服务特征写入数据完成--characteristic-----------{"service":"4A6E4000-5E16-459A-9E5B-86F23A314181","isBroadcasted":false,"uuid":"4A6E4001-5E16-459A-9E5B-86F23A314181","descriptors":{},"properties":"unknown","isNotifying":false,"peripheral":"58A1AA04-9BE7-6484-B9F0-CCA7DDD2D2EB"}
	 -----------向某服务特征写入数据完成--msgData-----------undefined
	 
	 
我想知道，我向蓝牙写入数据，收到通知了，但是里面只有 characteristic 是有值的；
msg 是undefine ，那我如何知道我的读写操作是否成功了呢

**Comment by Copypeng** [comment]
1，你应该描述的是

> -----------向某服务特征写入数据完成--msgData-----------undefined

中 msgData 为空？msg 不是你自己发的么，不能为空。注意问题描述。

2，这个通知里没有 error 就是写操作成功了。

你 body 打印一下就知道了，应该根本就没有第三个元素，你这么写法，body [2] 肯定永远是 undefined。
