### ISSUE TITLE
录制音频后，如何获取MHAudio.docPath下的音频文件内容

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/ios-rn-sdk#91]
我们通过MHAudio.startRecord对音频文件进行录制。

根据小米Demo，采用参数 MHAudio.docPath+'test.wav'  作为存储路径没有问题。但是录制后，没有找到相关方法获取到该文件的内容。尝试用MHPluginFS.readFileToBase64方法失败。

采用 MHPluginFS.storageBasePath + '/' + Math.random().toString(36).substr(2) + '.wav' 作为存储路径。 可以通过MHPluginFS.readFileToBase64方法找到相关文件内容。  但是在有些机子上没办法录制。没办法录制的机子回复信息：The audio recorder is not prepared!

请问，如果我们根据Demo中的例子，应该用什么方法才能获取到MHAudio.docPath下指定文件的内容呢？

**Comment by gaopingfly** [comment]
> 上个issue的根本原因是什么？

keyId和userId搞混了。分享钥匙用的userId，以为修改和删除用的也是userId，结果是keyId。我的问题。

请问这个怎么解决呢？

**Comment by Copypeng** [comment]
请更新上个issue。我认为耽误了大家时间，直接关闭不说明有点不负责任的意思。

**Comment by Copypeng** [comment]
这个 issue 的意图是什么呢？
录音成功之后会保存音频文件，根据模块 MHAudio 的文档说明，你是能获取到该文件的路径的，然后上传这个文件或者播放这个文件。你的需求是把文件读取成 UTF8 或者 Base64 编码的 String？

**Comment by gaopingfly** [comment]
> 这个 issue 的意图是什么呢？
> 录音成功之后会保存音频文件，根据模块 MHAudio 的文档说明，你是能获取到该文件的路径的，然后上传这个文件或者播放这个文件。你的需求是把文件读取成 UTF8 或者 Base64 编码的 String？

是的，我们需要拿到内容，发送给我们的蓝牙设备。

**Comment by LiuMengzhou** [comment]
@gaopingfly 我们新增了几个label，下次提issue加上label吧

**Comment by Copypeng** [comment]
可以尝试 MHPluginFS 模块中的 readFile 方法。这个方法会尝试读取文件内容，使用UTF8编码返回字符串。

**Comment by gaopingfly** [comment]
> @gaopingfly 我们新增了几个label，下次提issue加上label吧

好的，以后我提问加上标签

**Comment by gaopingfly** [comment]
> 可以尝试 MHPluginFS 模块中的 readFile 方法。这个方法会尝试读取文件内容，使用UTF8编码返回字符串。

好的，我们试验以下。感谢

**Comment by nevermore-jia** [comment]
我下载的文件是个zip包,解压后,是个文件夹,里面有多个文件,MHPluginFS这个模块没有提供响应的方法,读取文件.只能读取文件或者把zip包整体读取

**Comment by gaopingfly** [comment]
以前的方法好用多了，这个问题先关闭了
