### ISSUE TITLE
分享钥匙三大类型的几个问题，求解

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/ios-rn-sdk#92]
1、分享钥匙中，有类别是“暂时”，可设定钥匙“生效”和“过期”时间。请问：这里的“暂时”是指在有效期内，只能生效一次吗？

2、周期类别中，请问接口中的钥匙“生效”和“过期”时间是指“总共有效时间段”还是“生效日期当日的时间段”？

3、永久类别中，失效日期用不用设置？还是用Number.Max_value就好？

确认一下答案，由于蓝牙设备还没做好，手机端好提前做自己的业务逻辑。

**Comment by Copypeng** [comment]
好像跟sdk本身无关，是的产品定义问题。邀请PM处理吧。

**Comment by gaopingfly** [comment]
> 好像跟sdk本身无关，是的产品定义问题。邀请PM处理吧。

不是这样的。SDK上有说明，只是我对说明有点疑问，主要针对的是参数问题。你看看能不能帮忙解答一下。

以下是sdk说明
====================

shareSecureKey(did,shareUid,status,activeTime,expireTime,week,readonly,callback) AL-[125,)
分享设备电子钥匙，支持安全芯片的设备可调用

@param did 分享设备的did

@param shareUid 分享目标的uid

@param status 分享类别，1：暂时，2：周期，3：永久

@param activeTime 生效时间 UTC时间戳，单位为s

@param expireTime 过期时间 UTC时间戳，单位为s

@param week 生效日期（星期几，例如周一和周三对应1和3，[1, 3]），仅在status=2时不可为空

@param readonly 被分享人是否接受设备push，为 false 时接受，为 true 则不接受

@param callback

**Comment by gaopingfly** [comment]
算了，目前蓝牙钥匙还凑合能用。这问题时间也久了，关闭
