### ISSUE TITLE
多个ota升级文件

### ISSUE THREAD

**Issue by nevermore-jia** [MiEcosystem/ios-rn-sdk#95]
多个ota文件,下载到Documents/PluginStorage路径下,解压后,文件夹里面是多个文件,MHPluginFS没有响应的方法去读取文件.只能根据文件名读取PluginStorage路径下的.没法读取下一级路径下的文件

**Comment by LiuMengzhou** [comment]
@nevermore-jia 很高兴你提出issue。
`MHPluginFS`模块里面所有API的`filename`都可以写成“相对路径+文件名”的形式。
e.g.
`/targetFolder/targetFilename.xxx`

ps：下次提出issue按照模版填写吧，顺便加上label

**Comment by nevermore-jia** [comment]
readFileList 这个方法,并没有提供要传的参数(路径),那要怎么获取storageBasePath这个路径下,某文件夹下面的所有文件,然后根据名字(拼上相对路径),来读取里面的文件 @LiuMengzhou

**Comment by nevermore-jia** [comment]
1.我下载下来的文件,解压出来是个otaUpdate文件夹,它里面包含了M2_mcu_020204_20181006_release.bin这个文件
     2.分别尝试了用readFileToBase64和readeFile2个方法,其中fileName都分别传了下面3个路径都读取失败

otaUpdate/M2_mcu_020204_20181006_release.bin  /otaUpdate/M2_mcu_020204_20181006_release.bin  ./otaUpdate/M2_mcu_020204_20181006_release.bin 

  MHPluginFS.readFileToBase64('otaUpdate/M2_mcu_020204_20181006_release.bin', (success, utf8Content) => {
                console.log(success)
                console.log(utf8Content)
            })
