### ISSUE TITLE
writeBase64DataWithCallback 方法使用问题

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/ios-rn-sdk#97]
writeBase64DataWithCallback(data, characteristicUUID, serviceUUID, type, callback)

这个方法 的data 参数，有字节大小限制吗

假如我有一个2K 大小的data ，传进去发个蓝牙设备，蓝牙会怎么处理

writeHexDataWithCallback(hexString, characteristicUUID, serviceUUID, type, callback)  AL-[113,)

这个方法的 hexString ，有长度限制吗

**Comment by Copypeng** [comment]
都有长度限制，即 SDK 帮你做了 base64String 或 hexString 转换成 NSdata  的操作后，调用系统CoreBluetooth 框架的 Write 接口发送。系统限制不变。数据长度限制的讨论参考 https://github.com/MiEcosystem/ios-rn-sdk/issues/64

**Comment by hunter858** [comment]
@Copypeng 谢谢！
