### ISSUE TITLE
米家iOS插件页调用 loginXiaoMiBLE 接口时犯错错误码 4 (成功，一般不会出现在 error 中)

### ISSUE THREAD

**Issue by hilite2000** [MiEcosystem/ios-rn-sdk#98]
**check [docs](https://github.com/MiEcosystem/ios-rn-sdk/tree/master/MiHomePluginSDK/docs) before issue**

## Support Question

**环境条件**
- app版本: iOSv4.8.7
- 插件页: ver 0.4.1.806211
- 相关模块和API:  MHXiaomiBLE模块、 loginXiaoMiBLE

**问题描述**

上线设备，一周内至少三例用户联系收入如图的问题，用户声称以前是正常的。

产品model：shjszn.lock.c1

**使用方法**

你是如何使用SDK的？

**尝试过的解决办法**
删除设备重新添加，用户账号重新登录，都不能解决。
最终给用户更换设备。

**其他的上下文/日志/截图**

![snap35](https://user-images.githubusercontent.com/3259373/46722137-63287280-cca7-11e8-9c05-8a79efc029f3.jpg)

![snap1868](https://user-images.githubusercontent.com/3259373/46722301-c0bcbf00-cca7-11e8-8994-ccba0b229dc9.jpg)

**Comment by Copypeng** [comment]
你好，未能重现这个错误。并且我 review 了代码，确定了蓝牙 login 的 code == 4，有且只在登录成功时赋值。假如你们出现了登录失败，但是 code == 4 的情况，可能是隐藏的一个 bug。需要定位。

请贴一下 loginXiaoMiBLE 方法调用的具体代码，尤其是 callback 函数。以及返回的 callback 中 error 与 info 的值。方便更快速的定位。

**Comment by dzonel** [comment]
loginXiaoMiBLE的callback具体如下：
```
MHXiaomiBLE.loginXiaoMiBLE(device.did, device.mac, 15, (error, result) => {
    this.connectLockTimer && clearTimeout(this.connectLockTimer);
    if (!error) {
        this.setState({
            openPromptText:ZKOpenString.connectSuccessAndOpen,
            openPromptTextColor: '#2889fd',
        });
        this.currentDevice = result.device;
        this.openLockWithToggle();
    }else {
        var failReason = ZKOpenString.openFail + "（" + ZKCommonString.errorCode + "：" + error.code + "）";
        if (error.code == 6) {
            failReason = ZKCommonString.deviceHasBeenReset;
        }
        this.openFailWithMessage(failReason, ZKOpenString.notConnectedTheLockAndRetry);
    }
});
```
openLockWithToggle函数如下：
```
MHXiaomiBLE.toggleLockXiaoMiBLE(0, 10, (error, message)=>{
            if (error) {
                let errorMessage = ZKOpenString.openFail + '（' + ZKCommonString.errorCode + '：' + error.code + '）';
                this.openFailWithMessage(errorMessage, ZKOpenString.notConnectedTheLockAndRetry);
                return;
            }
            var responseCodeHex = message.response;
            var responseCode = -1;
            if (responseCodeHex) {
                responseCode = parseInt(responseCodeHex, 16);
            }
            if (responseCode == 0x02) {
                this.openFailWithMessage(ZKOpenString.theDoorWasLocked + '(' + ZKCommonString.errorCode + '：0x02)', ZKOpenString.clickUnlock);
                return;
            }
            if (responseCode == 0x7F) {
                this._openSuc();
                this.setState({
                    openPromptText:ZKOpenString.theDoorOpenDoubleVerify,
                    openPromptTextColor: '#83C073',
                });
                return;
            }
            this._openSuc();
        });
```
至于loginXiaoMiBLE返回的 callback 中 error 与 info 的值暂不能提供，因其出现于用户实际使用中。

**Comment by hilite2000** [comment]
近一周有三起此问题的报告

**Comment by hilite2000** [comment]
重新上电后，换了一个账号和手机可以绑定上，并能正常操作了。又绑回原账号也正常了。
是否是因为更换账号而解决的，不确定。

**Comment by hunter858** [comment]
@Copypeng 我们在插件退出的时候 有调用 MHXiaomiBLE.disconnectXiaoMiBLE(did, mac, callback) 这个方法，确定是调用成功了，就是有时候蓝牙不太稳定，个别设备连接特别困难，不过最近一段时间升级了新的固件，好了一些

**Comment by Copypeng** [comment]
经多月观察未发现类似问题，未能重现。关闭issue。
